const strings = {
  pt: {
    // Nav
    history: 'Histórico',
    settings: 'Definições',
    exercisesTitle: 'Exercícios',

    // Home
    homeTitle: 'Treino',
    restDay: 'Dia de Descanso',
    startWorkout: 'Iniciar',
    startAnother: 'Outro treino',
    days: 'dias',
    steps: 'Passos',
    noWorkoutScheduled: 'Sem treino agendado',
    noPlan: 'Sem plano ativo',
    choosePlan: 'Escolher plano',

    // Active workout
    end: 'Terminar',
    cancel: 'Cancelar',
    endWorkout: 'Terminar treino',
    cancelWorkout: 'Cancelar treino',
    minimize: 'Minimizar',
    endConfirm: 'Queres terminar este treino?',
    noSetsDone: 'Nenhuma série concluída. Não podes guardar.',
    cancelConfirm: 'Queres cancelar? O progresso será perdido.',
    workoutChangedTitle: 'Treino diferente do modelo',
    workoutChangedMessage: 'Os exercícios ficaram diferentes de "{name}". Queres guardar as alterações no treino?',
    discardChanges: 'Não guardar',
    addExercise: 'Exercício',
    reps: 'Reps',
    weight: 'Peso (kg)',
    done: 'Concluído',
    rest: 'Descanso',
    restTimer: 'Temporizador de descanso',
    restTimerDone: 'Descanso terminado!',
    startRest: 'Iniciar',
    dragToAdjust: 'Arrasta para ajustar',
    skipRest: 'Saltar',
    oneRM: 'Calcular 1RM',
    oneRMResult: '1RM estimado',
    workoutDone: 'Treino concluído!',
    totalTime: 'Tempo total',
    totalSets: 'Séries totais',
    totalVolume: 'Volume total',
    great: 'Ótimo trabalho!',
    close: 'Fechar',
    seconds: 's',
    minutes: 'min',

    // Exercises modal
    searchExercises: 'Pesquisar exercícios...',
    allTags: 'Todos',
    noResults: 'Sem resultados',
    filters: 'Filtros',
    filterBodyPart: 'Parte do corpo',
    filterEquipment: 'Equipamento',
    rotateBody: 'Rodar',
    clearFilters: 'Limpar',
    applyFilters: 'Aplicar',
    noMediaYet: 'Vídeo em breve',
    instructions: 'Instruções',
    variantsTitle: 'Variantes',
    category: 'Categoria',
    primaryMuscle: 'Músculo principal',
    secondaryMusclesLabel: 'Músculos secundários',
    toggleCardView: 'Ver em cartões',
    toggleListView: 'Ver em lista',

    // Custom exercise
    createCustomExercise: 'Criar exercício',
    customExerciseBadge: 'Personalizado',
    exerciseName: 'Nome do exercício',
    repUnitLabel: 'Unidade',
    unitReps: 'Reps',
    unitMeters: 'Metros',
    defaultSetsLabel: 'Séries padrão',
    defaultRepsLabel: 'Reps padrão',
    exerciseDescriptionLabel: 'Descrição',
    viewOnBody: 'Ver no corpo',

    // History
    noHistory: 'Sem histórico ainda',
    historyEmpty: 'Completa um treino para começar.',
    volume: 'volume',
    sets: 'séries',
    exercises: 'exercícios',
    importWorkoutTitle: 'Importar treino?',
    importWorkout: 'Importar',
    setTypeNormal: 'Normal',
    setType_warmup: 'Aquecimento',
    setType_dropset: 'Dropset',
    setType_superset: 'Super-série',
    setType_failure: 'Falha',

    // Plan settings
    plans: 'Planos',
    newPlan: 'Novo plano',
    activePlan: 'Plano ativo',
    setActive: 'Definir como ativo',
    editPlan: 'Editar plano',
    editWorkout: 'Editar treino',
    activeWorkoutEditTitle: 'Treino em curso',
    activeWorkoutEditMessage: 'Este treino está ativo agora. Queres guardar as alterações?',
    planName: 'Nome do plano',
    workoutDay: 'Treino',
    dayRest: 'Descanso',
    selectWorkout: 'Selecionar treino',
    workouts: 'Treinos',
    newWorkout: 'Novo treino',
    workoutName: 'Nome do treino',
    exerciseNote: 'Nota',
    save: 'Guardar',
    delete: 'Eliminar',
    back: 'Voltar',
    confirm: 'Confirmar',

    // Steps modal
    stepsToday: 'Passos de hoje',
    stepsPlaceholder: 'ex. 8500',
    saveSteps: 'Guardar',


    // Profile
    profileTitle: 'Perfil',
    measures: 'Medidas',
    duration: 'Duração',
    weeklyProgress: 'Progresso semanal',

    // Statistics page
    daysTrained: 'Dias treinados',
    totalSessions: 'Treinos totais',
    totalReps: 'Reps totais',
    bestStreak: 'Melhor série',
    personalRecords: 'Recordes pessoais',
    personalRecordsLegend: '1RM estimado',
    muscleDistribution: 'Distribuição muscular',
    noPRs: 'Ainda sem recordes',
    customizeStats: 'Personalizar',
    doneEditing: 'Concluído',
    statsBlock_tiles: 'Resumo de treino',
    statsBlock_streakCalendar: 'Calendário de sequência',
    statsBlock_steps: 'Passos',
    progress: 'Progresso',
    noSessionsYet: 'Ainda sem treinos registados.',
    noStatsEnabled: 'Nenhuma estatística ativa — toca em Personalizar para ligar blocos',
    muscleFatigue: 'Fadiga muscular',
    fatigueLevel_fatigued: 'Fatigado',
    fatigueLevel_recovering: 'A recuperar',
    fatigueLevel_fresh: 'Fresco',
    fatigueLevel_none: 'Sem dados',
    daysAgo: 'há {n}d',

    // Measures page
    measureValuePlaceholder: 'Valor',
    saveMeasure: 'Guardar',
    noMeasures: 'Sem medidas registadas',
    progression: 'Progressão',
    measureInvalidValue: 'Valor inválido',
    measureSaveFailed: 'Não foi possível guardar',
    // Custom measure types
    measureAddType: 'Nova medida',
    measureAddTypeAria: 'Adicionar parte do corpo',
    measureAddTypePill: '+ Adicionar',
    measureTypeGroupLabel: 'Grupo',
    measureTypeNewGroup: 'Criar grupo novo',
    measureTypeNewGroupName: 'Nome do grupo',
    measureTypeNameLabel: 'Parte do corpo',
    measureTypeNamePlaceholder: 'ex. Gémeo esquerdo',
    measureTypeNameRequired: 'Escreve o nome da parte do corpo.',
    measureTypeDuplicate: 'Já existe uma medida com esse nome.',
    measureTypeGroupRequired: 'Escreve o nome do grupo.',
    measureTypeUnitLabel: 'Unidade',
    measureTypeUnitOther: 'Outra',
    measureTypeUnitPlaceholder: 'ex. bpm',
    measureTypeUnitRequired: 'Escreve a unidade.',
    measureTypeYours: 'As tuas medidas',
    deleteMeasureTypeTitle: 'Eliminar esta medida?',
    deleteMeasureTypeMessage: 'Os valores já registados nesta medida também são eliminados.',
    measureGroup_general: 'Geral',
    measureGroup_torso: 'Tronco',
    measureGroup_arms: 'Braços',
    measureGroup_legs: 'Pernas',
    measureType_weight: 'Peso',
    measureType_height: 'Altura',
    measureType_bodyFat: 'Massa gorda',
    measureType_chest: 'Peito',
    measureType_waist: 'Cintura',
    measureType_hips: 'Quadris',
    measureType_neck: 'Pescoço',
    measureType_shoulders: 'Ombros',
    measureType_biceps: 'Bíceps',
    measureType_forearm: 'Antebraço',
    measureType_quadriceps: 'Quadricípite',
    measureType_calves: 'Gémeos',

    // Themes / lang
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
    accentColor: 'Cor principal',
    colorGreen: 'Verde',
    colorBlue: 'Azul',
    colorPurple: 'Roxo',
    colorPink: 'Rosa',
    colorRed: 'Vermelho',
    colorOrange: 'Laranja',
    fontSize: 'Tamanho do texto',
    fontSizeSmall: 'Pequeno',
    fontSizeMedium: 'Médio',
    fontSizeLarge: 'Grande',
    fontSizeExtraLarge: 'Extra grande',
    sound: 'Som',
    soundToggle: 'Sons da app',
    language: 'Idioma',
    langPt: 'Português',
    langEn: 'English',

    // Settings
    settingsTitle: 'Definições',
    settingsSections: 'Secções',
    settingsSectionsDesc: 'Escolhe que partes da app aparecem na navegação.',
    sectionGym: 'Treino',
    dataSection: 'Os teus dados',
    dataSectionDesc: 'Guarda uma cópia completa ou só os treinos, e traz dados de volta.',
    exportData: 'Guardar cópia',
    exportDataDesc: 'Escolhe o que queres guardar',
    exportChoiceQuestion: 'O que queres guardar?',
    exportChoiceFull: 'Cópia completa (JSON)',
    exportChoiceFullDesc: 'Tudo: treinos, planos, medidas, nutrição e definições',
    exportCsv: 'Só os treinos (CSV)',
    exportCsvDesc: 'Uma linha por série, para o Excel ou outra app',
    importCsv: 'Importar',
    importCsvDesc: 'De uma cópia da BeefUp ou de outra app',
    importChoiceQuestion: 'De onde vem o ficheiro?',
    importSourceBeefUp: 'Cópia da BeefUp (CSV)',
    importSourceBeefUpDesc: 'Repõe os treinos tal e qual, sem duplicar',
    importSourceOther: 'Outra app (CSV)',
    importSourceOtherDesc: 'Strong, Hevy e afins — os exercícios são reconhecidos pelo nome',
    importSourceJson: 'Cópia completa (JSON)',
    importSourceJsonDesc: 'Restaura tudo — substitui os dados atuais',
    importBackupTitle: 'Restaurar cópia?',
    importBackupWarn: 'Isto apaga os dados atuais e põe no lugar os do ficheiro. Não dá para desfazer.',
    restore: 'Restaurar',
    importDone: 'Importados {w} treinos e {s} séries.',
    importFailed: 'Não foi possível concluir a operação. Tenta novamente.',
    unmatchedExercises: '{n} exercícios não reconhecidos ficaram com o nome original.',
    csvNotBeefUp: 'Este ficheiro não é uma cópia da BeefUp. Tenta a opção "Outra app".',
    csvNoColumns: 'Não encontrei as colunas de exercício, data e séries neste CSV.',

    // Nutrition
    nutrition: 'Nutrição',
    calories: 'Calorias',
    kcal: 'kcal',
    protein: 'Proteína',
    carbs: 'Hidratos',
    fat: 'Gordura',
    fiber: 'Fibra',
    sugar: 'Açúcar',
    saturatedFat: 'Gordura saturada',
    transFat: 'Gordura trans',
    sodium: 'Sódio',
    potassium: 'Potássio',
    calcium: 'Cálcio',
    iron: 'Ferro',
    moreDetails: 'Mais detalhes',
    noData: 'sem dados',
    searchingFood: 'A pesquisar...',
    typeToSearch: 'Escreve para pesquisar alimentos',
    foodSearchFailed: 'Não foi possível pesquisar. Verifica a ligação.',
    foodSearchLimit: 'Demasiadas pesquisas. Aguarda {n}s.',
    retry: 'Tentar novamente',
    goal: 'Objetivo',
    water: 'Água',
    addWater: 'Adicionar copo',
    meals: 'Refeições',
    breakfast: 'Pequeno-almoço',
    morningSnack: 'Lanche da manhã',
    lunch: 'Almoço',
    afternoonSnack: 'Lanche da tarde',
    dinner: 'Jantar',
    snack: 'Lanche',
    newMeal: 'Nova refeição',
    mealName: 'Nome da refeição',
    deleteMealTitle: 'Eliminar refeição?',
    deleteMealConfirm: 'Isto elimina "{name}" da lista. Os registos já feitos não são apagados.',
    addFood: 'Adicionar alimento',
    searchFood: 'Pesquisar alimentos...',
    searchOnline: 'Procurar marcas online',
    insaCredit: 'Fonte: Base de Dados da Composição de Alimentos. Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P. - INSA. v 7.1 - 2026',
    scanBarcode: 'Ler código de barras',
    scanPreparingCamera: 'A preparar câmara...',
    scanAimAtBarcode: 'Aponta a câmara ao código de barras',
    scanProductNotFound: 'Produto não encontrado.',
    scanTryAgain: 'Tentar de novo',
    scanCameraDenied: 'Sem acesso à câmara. Autoriza nas definições do browser.',
    scanNoCamera: 'Nenhuma câmara encontrada.',
    serving: 'Porção',
    grams: 'Gramas',
    units: 'Unidades',
    quantity: 'Quantidade',
    customFood: 'Alimento personalizado',
    foodName: 'Nome do alimento',
    add: 'Adicionar',
    editGoals: 'Editar objetivos',
    editMealsList: 'Editar refeições',
    nutritionGoals: 'Objetivos nutricionais',
    calculator: 'Calculadora',
    manual: 'Manual',
    age: 'Idade',
    height: 'Altura (cm)',
    bodyWeight: 'Peso (kg)',
    sex: 'Sexo',
    male: 'Masculino',
    female: 'Feminino',
    activity: 'Atividade',
    actSedentary: 'Sedentário',
    actLight: 'Leve',
    actModerate: 'Moderado',
    actActive: 'Ativo',
    actVeryActive: 'Muito ativo',
    actFromWorkout: 'Obter dos treinos',
    objCut: 'Perder',
    objMaintain: 'Manter',
    objBulk: 'Ganhar',
    calculate: 'Calcular',
    glasses: 'copos',
    proteinShort: 'P',
    carbsShort: 'H',
    fatShort: 'G',
    deleteFoodTitle: 'Eliminar registo?',
    deleteFoodConfirm: 'Isto elimina "{name}" do dia de hoje.',
    deleteCustomFoodTitle: 'Eliminar alimento?',
    deleteCustomFoodConfirm: 'Isto elimina "{name}" da tua lista de alimentos personalizados.',
    deleteCustomExerciseTitle: 'Eliminar exercício?',
    deleteCustomExerciseConfirm: 'Isto elimina "{name}" dos teus exercícios personalizados.',
    macrosFromGoal: 'Macros dão {kcal} kcal',
    favouriteFood: 'Marcar como favorito',

    // Onboarding
    obWelcome: 'BeefUp',
    obWelcomeSub: 'Como queres usar a app?',
    obStart: 'Começar',
    obStartDesc: 'Treina e acompanha-te a ti próprio',
    obHelping: 'Estou a ajudar outros',
    obHelpingDesc: 'Gere clientes como treinador',
    obFocusTitle: 'Para que vais usar a app?',
    obFocusGym: 'Ginásio',
    obFocusGymDesc: 'Planos e treinos',
    obFocusNutrition: 'Nutrição',
    obFocusNutritionDesc: 'Calorias e macros',
    obFocusBoth: 'Ambos',
    obFocusBothDesc: 'Treino e dieta juntos',
    obMeasuresTitle: 'As tuas medidas',
    obMeasuresSub: 'Opcional, podes saltar qualquer campo',
    obGoalsTitle: 'O teu objetivo',
    obNext: 'Seguinte',
    obSkip: 'Saltar',
    obFinish: 'Concluir',
    obHelperCreateAccount: 'Cria a tua conta de treinador',
    obHelperSignIn: 'Entra na tua conta de treinador',
    obHelperAccountWhy: 'Precisas de conta para os teus clientes se poderem ligar a ti e os dados deles te chegarem.',
    obHelperContinue: 'Continuar',
    obHelperAccountFailed: 'Não foi possível continuar. Verifica os dados.',
    obHelperConfirmEmail: 'Conta criada. Confirma o teu email antes de continuares (verifica a caixa de entrada).',
    // Explainers
    obExpGymTitle: 'Treinos sempre contigo',
    obExpGymBody: 'Cria planos, regista séries e vê a tua progressão ao longo do tempo.',
    obExpNutritionTitle: 'Nutrição simples',
    obExpNutritionBody: 'Acompanha calorias, macros e água com objetivos calculados para ti.',
    obExpMeasuresTitle: 'Vê o teu progresso',
    obExpMeasuresBody: 'Registar medidas ajuda-te a ver resultados reais, não só na balança.',
    obExpGoalsTitle: 'Tudo definido',
    obExpGoalsBody: 'Os teus objetivos nutricionais estão prontos. Vamos começar!',
    obLoadPlanTitle: 'Plano pré-feito?',
    obLoadPlanSub: 'Podes começar já com um plano, ou criar o teu do zero.',
    obLoadPlanYes: 'Sim, carregar Push Pull Legs',
    obLoadPlanYesDesc: '3 treinos e plano semanal prontos a usar',
    obLoadPlanNo: 'Não, começo do zero',
    obLoadPlanNoDesc: 'Crio os meus próprios treinos e plano',

    // Coach dashboard
    dashCalendar: 'Calendário',
    previousMonth: 'Mês anterior',
    nextMonth: 'Mês seguinte',
    dashClients: 'Alunos',
    dashInviteClient: 'Convidar aluno',
    dashNoClients: 'Ainda não tens alunos ligados.',
    dashSelectClient: 'Escolhe um aluno à esquerda.',
    dashNotes: 'Notas',
    dashNotesPlaceholder: 'Escrever nota sobre o aluno...',
    dashAssign: 'Atribuir',
    dashApptType: 'Tipo',
    dashApptConsulta: 'Consulta',
    dashApptTreino: 'Treino',
    dashApptRotina: 'Rotina',
    dashSelectTimeTitle: 'Selecionar hora',
    dashTimeOk: 'OK',
    dashTimeKeyboardToggle: 'Inserir hora manualmente',
    dashUpcoming: 'Próximos',
    dashFilterAll: 'Geral',
    dashNoUpcoming: 'Sem marcações futuras.',
    dashUnassigned: 'Sem nada agendado',
    dashGym: 'Ginásio',
    dashMeasures: 'Medidas',
    dashMeasuresLogTab: 'Registo',
    dashMeasuresGoalsTab: 'Objetivos',
    dashMeasureGoalsDesc: 'Objetivos que defines aparecem na app do aluno; ele não os pode alterar.',
    dashMeasureGoalDefine: '+ Definir objetivo',
    dashMeasureGoalPlaceholder: 'Valor alvo',
    deleteMeasureGoalTitle: 'Remover este objetivo?',
    dashNoMeasureGoals: 'Ainda não definiste nenhum objetivo para este aluno.',
    dashMeasureGoalNoData: 'Regista um valor para veres o progresso.',
    dashMeasureGoalReached: 'Atingido',
    dashMeasureGoalsMore: '+{n} objetivos',
    dashOverview: 'Resumo',
    dashTime: 'Hora',
    dashSync: 'Sincronizar',
    // Conta do treinador e códigos de convite
    dashAccount: 'Conta',
    dashSyncUnavailable: 'Sincronização não disponível.',
    dashSignIn: 'Iniciar sessão',
    dashSignUp: 'Criar conta',
    dashDisplayName: 'Nome',
    dashEmail: 'Email',
    dashPassword: 'Palavra-passe',
    dashNeedAccount: 'Ainda não tens conta? Criar uma',
    dashHaveAccount: 'Já tens conta? Iniciar sessão',
    dashConnected: 'Ligado',
    dashSignOut: 'Terminar sessão',
    dashInvites: 'Convites',
    dashInvitesDesc: 'Gera um convite e envia o link ao aluno. É o link que o liga a ti — o código sozinho não chega, serve só para o identificares e revogares aqui.',
    dashNewInvite: 'Novo convite',
    dashNoInvites: 'Sem convites ativos',
    dashCopyInviteLink: 'Copiar link de convite',
    dashCopyLink: 'Copiar link',
    dashCopied: 'Copiado!',
    dashInviteCodeLabel: 'código',
    dashInviteLinkUnavailable: 'Não foi possível criar o link (configuração em falta).',
    dashRevoke: 'Revogar',
    dashRevokeInviteTitle: 'Revogar este código?',
    dashLinked: 'Ligado',
    dashSessions: 'Sessões',
    dashNutrition: 'Nutrição',
    dashNothingShared: 'O aluno ainda não partilhou dados.',
    // Prescrever treinos e desligar um aluno
    dashPrescribeDesc: 'Treinos que prescreves aparecem na app do aluno e ele não os pode alterar.',
    dashNoWorkouts: 'Este aluno ainda não tem treinos.',
    dashPrescribeWorkout: '+ Prescrever treino',
    dashPrescribedByYou: 'prescrito por ti',
    dashClientOwn: 'do próprio aluno',
    dashUnprescribeTitle: 'Retirar "{name}"?',
    dashUnprescribeMessage: 'O treino desaparece da app do aluno na próxima sincronização. O histórico de treinos já feitos não é afetado.',
    dashPrescribePlanDesc: 'O plano semanal que montas aparece na app do aluno; ele escolhe-o como plano ativo.',
    dashNoPlan: 'Ainda não atribuíste um plano a este aluno.',
    dashPrescribePlan: '+ Criar plano',
    dashUnprescribePlanTitle: 'Retirar o plano?',
    dashUnprescribePlanMessage: 'O plano desaparece da app do aluno na próxima sincronização.',
    dashPrescribeGoalsDesc: 'Os objetivos que defines aparecem na app do aluno; ele não os pode alterar enquanto estiverem ativos.',
    dashNoGoals: 'Ainda não definiste objetivos nutricionais para este aluno.',
    dashPrescribeGoals: '+ Definir objetivos',
    dashUnprescribeGoalsTitle: 'Retirar os objetivos?',
    dashUnprescribeGoalsMessage: 'Os objetivos desaparecem da app do aluno na próxima sincronização; ele volta aos seus próprios.',
    dashNoNutritionData: 'Este aluno ainda não registou refeições.',
    dashPrevDay: 'Dia anterior',
    dashNextDay: 'Dia seguinte',
    dashPlanTab: 'Plano',
    dashDailyData: 'Dados diários',
    dashScopeNotShared: 'O aluno ainda não partilhou esta parte contigo. Ele pode ativá-la nas definições da app dele.',
    dashSearchClients: 'Procurar aluno',
    dashNoSessions: 'Este aluno ainda não registou treinos.',
    dashNoMeals: 'Nada registado neste dia.',
    dashLastSession: 'último a',
    dashNoAppointment: 'Sem marcação agendada.',
    dashNoNotes: 'Ainda não escreveste notas sobre este aluno.',
    micronutrients: 'Micronutrientes',
    dashUnlinkClient: 'Desligar aluno',
    dashUnlinkClientTitle: 'Desligar {name}?',
    dashUnlinkClientMessage: 'Deixas de ver os dados deste aluno. Os dados dele não são apagados, e ele pode voltar a ligar-se com um código novo.',
    // Ligação do aluno a um treinador
    trainerSectionTitle: 'Treinador Pessoal',
    trainerUnavailable: 'A ligação a um treinador não está disponível nesta instalação.',
    trainerLinkExplain: 'O treinador vai poder ver o que escolheres partilhar, e vai ser criada uma conta para ti.',
    trainerLinkButton: 'Ligar a um treinador',
    trainerSyncStatusOff: 'Sincronização desligada',
    trainerSyncStatusIdle: 'Sincronizado',
    trainerSyncStatusSyncing: 'A sincronizar…',
    trainerSyncStatusOffline: 'Sem ligação',
    trainerSyncStatusError: 'Erro de sincronização',
    trainerLastSyncedAt: 'Última sincronização: {time}',
    trainerNeverSynced: 'Ainda não sincronizado',
    trainerSyncNowLabel: 'Sincronizar agora',
    trainerShareSectionTitle: 'O que partilhas',
    trainerScopesNote: 'Podes mudar isto sempre que quiseres.',
    trainerScopeUpdateFailed: 'Não foi possível atualizar. Tenta novamente.',
    trainerUnlinkButton: 'Deixar de partilhar com o treinador',
    trainerUnlinkTitle: 'Deixar de partilhar?',
    trainerUnlinkMessage: 'O treinador deixa de conseguir ver os teus dados. Os teus dados guardados nesta app não são apagados, e a tua conta de acesso mantém-se criada.',
    trainerUnlinkFailed: 'Não foi possível terminar a ligação. Tenta novamente.',
    trainerLinkStep: 'Passo {n} de {total}',
    trainerLinkNeedsInvite: 'Precisas de um link de convite do teu treinador para te ligares. Um código sozinho já não chega — pede-lhe para te enviar o link.',
    trainerLinkScopesTitle: 'O que vais partilhar',
    trainerLinkScopesExplain: 'Escolhe o que o treinador vai poder ver. Podes mudar isto sempre que quiseres.',
    trainerLinkConnectExplain: 'Este convite liga-te ao seguinte servidor. Confirma antes de continuar.',
    trainerLinkConnectHostLabel: 'Servidor',
    trainerLinkConnectSchemaMissing: 'Este servidor ainda não está pronto para receber ligações. Avisa o teu treinador.',
    trainerLinkConnectUnreachable: 'Não foi possível contactar este servidor. Verifica a tua ligação e tenta novamente.',
    trainerLinkConnectUnknown: 'Não foi possível confirmar este servidor. Tenta novamente.',
    trainerLinkConnectInvalidLink: 'Este link não parece válido. Pede ao teu treinador um novo link.',
    trainerLinkAccountExplain: 'Precisamos de criar uma conta para os teus dados chegarem ao treinador.',
    trainerLinkSignInExplain: 'Entra com a conta que já usas com este treinador.',
    trainerLinkHaveAccount: 'Já tenho conta — entrar',
    trainerLinkNeedAccount: 'Não tenho conta — criar',
    trainerLinkEmailLabel: 'Email',
    trainerLinkPasswordLabel: 'Palavra-passe',
    trainerLinkConfirmExplain: 'Confirma os dados antes de ligar.',
    trainerLinkScopesNone: 'Nada selecionado',
    trainerLinkNext: 'Seguinte',
    trainerLinkSuccessTitle: 'Ligado a {name}',
    trainerLinkSuccessDesc: 'A partir de agora, o treinador vê o que escolheste partilhar.',
    trainerLinkScopesPending: 'Ligação criada, mas as opções de partilha não ficaram guardadas. Ainda não estás a partilhar nada — ajusta nas Definições.',
    trainerSetupIntroTitle: 'O teu próprio projeto Supabase',
    trainerSetupIntroBody: 'Cada treinador cria e controla o seu próprio projeto na Supabase — é aí que os dados dos teus clientes ficam guardados, não nos nossos servidores. Vamos criar e ligar o teu em poucos passos.',
    trainerSetupProjectTitle: 'Cria um projeto',
    trainerSetupProjectBody: 'Abre a Supabase, cria uma conta se ainda não tiveres, e cria um novo projeto (grátis). Pode demorar um a dois minutos a ficar pronto — volta aqui depois.',
    trainerSetupProjectLink: 'Abrir supabase.com',
    trainerSetupSqlTitle: 'Configura a base de dados',
    trainerSetupSqlBody: 'No teu projeto, abre o editor SQL, cola o script abaixo e executa-o. Isto cria as tabelas e regras de que a app precisa.',
    trainerSetupCopySql: 'Copiar script SQL',
    trainerSetupSqlCopyFailed: 'Não foi possível copiar. Tenta selecionar e copiar manualmente.',
    trainerSetupSqlEditorLink: 'Abrir editor SQL',
    trainerSetupCredentialsTitle: 'Liga o teu projeto',
    trainerSetupCredentialsBody: 'No teu projeto, vai a Definições > API e cola aqui o URL e a chave "anon public".',
    trainerSetupUrlLabel: 'URL do projeto',
    trainerSetupKeyLabel: 'Chave anon',
    trainerSetupConnectButton: 'Testar e ligar',
    trainerSetupInvalidConfig: 'Isto não parece um URL ou chave válidos de um projeto Supabase.',
    trainerSetupSchemaMissing: 'Este projeto ainda não tem o script SQL executado. Copia-o e corre-o no editor SQL do teu projeto.',
    trainerSetupUnreachable: 'Não foi possível contactar este projeto. Verifica a tua ligação e o URL.',
    trainerSetupTestUnknown: 'Não foi possível confirmar este projeto. Tenta novamente.',
    trainerSetupTrainerTaken: 'Este projeto já tem um treinador associado. Usa a conta original ou cria outro projeto.',
    prescribedBadge: 'prescrito pelo treinador',
    prescribedLocked: 'Prescrito pelo treinador, não editável',
    // Moved out of inline lang ternaries
    advanced: "Avançado",
    bodyBack: "Costas",
    bodyFront: "Frente",
    choose: "Escolher",
    copySuffix: "cópia",
    createNewWorkout: "+ Criar novo treino",
    currentPlan: "Plano Atual",
    currentStreak: "Sequência atual",
    currentStreakShort: "Sequência atual",
    bestStreakLabel: "Melhor: {n} dias",
    daysTitle: "Dias",
    toggleDayType: "Alternar tipo de dia",
    deleteWorkoutAction: "Eliminar",
    demoPresetTitle: "Carregar exemplo",
    demoPresetDesc: "Plano e treinos de exemplo (Push Pull Legs)",
    demoPresetLoaded: "Exemplo carregado.",
    duplicate: "Duplicar",
    edit: "Editar",
    load: "Carregar",
    loading: "A carregar",
    myWorkouts: "Os meus Treinos",
    newPersonalRecord: "Novo recorde pessoal!",
    noActivePlanTap: "Nenhum plano ativo — toca para criar",
    noExercises: "Sem exercícios.",
    noExercisesYet: "Sem exercícios ainda.",
    noWorkoutsThisWeek: "Sem treinos esta semana ainda.",
    rename: "Renomear",
    renameWorkoutPrompt: "Novo nome do treino:",
    deleteWorkoutTitle: 'Eliminar "{name}"?',
    cannotUndo: "Esta ação não pode ser desfeita.",
    deletePlanTitle: 'Eliminar "{name}"?',
    deleteMeasureTitle: "Eliminar medida?",
    deleteNoteTitle: "Eliminar nota?",
    deletePlanDayTitle: "Remover este dia do plano?",
    deleteAppointmentTitle: "Eliminar marcação?",
    removeExerciseTitle: "Remover exercício?",
    removeExerciseConfirm: "Remove o exercício e todas as séries registadas nele, neste treino.",
    restDayBody: "Recupera e volta mais forte.",
    setSingular: "Série",
    share: "Partilhar",
    startWorkoutAria: "Iniciar treino",
    valuesPer100g: "Valores por 100 g",
    weekMuscles: "Músculos esta semana",
    pwaInstallTitle: 'Instalar a BeefUp',
    pwaInstallDesc: 'Adiciona a app ao teu dispositivo e usa-a offline.',
    pwaInstall: 'Instalar',
    pwaInstallIosDesc: 'Toca em Partilhar e depois em "Adicionar ao ecrã principal".',
    pwaUpdateTitle: 'Nova versão disponível',
    pwaUpdateDesc: 'Recarrega para atualizar a app.',
    pwaUpdate: 'Atualizar',
    pwaOfflineReady: 'App pronta para funcionar offline.',
    pwaDismiss: 'Agora não',

  },

  en: {
    history: 'History',
    settings: 'Settings',
    exercisesTitle: 'Exercises',

    homeTitle: 'Workout',
    restDay: 'Rest Day',
    startWorkout: 'Start',
    startAnother: 'Another workout',
    days: 'days',
    steps: 'Steps',
    noWorkoutScheduled: 'No workout scheduled',
    noPlan: 'No active plan',
    choosePlan: 'Choose plan',

    end: 'End',
    cancel: 'Cancel',
    endWorkout: 'End Workout',
    cancelWorkout: 'Cancel Workout',
    minimize: 'Minimize',
    endConfirm: 'End this workout?',
    noSetsDone: 'No sets done. Cannot save.',
    cancelConfirm: 'Cancel? All progress will be lost.',
    workoutChangedTitle: 'Workout differs from template',
    workoutChangedMessage: 'The exercises ended up different from "{name}". Save the changes to the workout?',
    discardChanges: "Don't save",
    addExercise: 'Exercise',
    reps: 'Reps',
    weight: 'Weight (kg)',
    done: 'Done',
    rest: 'Rest',
    restTimer: 'Rest timer',
    restTimerDone: 'Rest over!',
    startRest: 'Start',
    dragToAdjust: 'Drag to adjust',
    skipRest: 'Skip',
    oneRM: 'Calculate 1RM',
    oneRMResult: 'Estimated 1RM',
    workoutDone: 'Workout complete!',
    totalTime: 'Total time',
    totalSets: 'Total sets',
    totalVolume: 'Total volume',
    great: 'Great work!',
    close: 'Close',
    seconds: 's',
    minutes: 'min',

    searchExercises: 'Search exercises...',
    allTags: 'All',
    noResults: 'No results',
    filters: 'Filters',
    filterBodyPart: 'Body part',
    filterEquipment: 'Equipment',
    rotateBody: 'Rotate',
    clearFilters: 'Clear',
    applyFilters: 'Apply',
    noMediaYet: 'Video coming soon',
    instructions: 'Instructions',
    variantsTitle: 'Variants',
    category: 'Category',
    primaryMuscle: 'Primary muscle',
    secondaryMusclesLabel: 'Secondary muscles',
    toggleCardView: 'Card view',
    toggleListView: 'List view',

    createCustomExercise: 'Create exercise',
    customExerciseBadge: 'Custom',
    exerciseName: 'Exercise name',
    repUnitLabel: 'Unit',
    unitReps: 'Reps',
    unitMeters: 'Meters',
    defaultSetsLabel: 'Default sets',
    defaultRepsLabel: 'Default reps',
    exerciseDescriptionLabel: 'Description',
    viewOnBody: 'View on body',

    noHistory: 'No history yet',
    historyEmpty: 'Complete a workout to get started.',
    volume: 'volume',
    sets: 'sets',
    exercises: 'exercises',
    importWorkoutTitle: 'Import workout?',
    importWorkout: 'Import',
    setTypeNormal: 'Normal',
    setType_warmup: 'Warmup',
    setType_dropset: 'Dropset',
    setType_superset: 'Superset',
    setType_failure: 'Failure',

    plans: 'Plans',
    newPlan: 'New plan',
    activePlan: 'Active plan',
    setActive: 'Set as active',
    editPlan: 'Edit plan',
    editWorkout: 'Edit workout',
    activeWorkoutEditTitle: 'Workout in progress',
    activeWorkoutEditMessage: 'This workout is active right now. Do you want to save the changes?',
    planName: 'Plan name',
    workoutDay: 'Workout',
    dayRest: 'Rest',
    selectWorkout: 'Select workout',
    workouts: 'Workouts',
    newWorkout: 'New workout',
    workoutName: 'Workout name',
    exerciseNote: 'Note',
    save: 'Save',
    delete: 'Delete',
    back: 'Back',
    confirm: 'Confirm',

    stepsToday: "Today's steps",
    stepsPlaceholder: 'e.g. 8500',
    saveSteps: 'Save',

    // Profile
    profileTitle: 'Profile',
    measures: 'Measures',
    duration: 'Duration',
    weeklyProgress: 'Weekly progress',

    // Statistics page
    daysTrained: 'Days trained',
    totalSessions: 'Total sessions',
    totalReps: 'Total reps',
    bestStreak: 'Best streak',
    personalRecords: 'Personal records',
    personalRecordsLegend: 'estimated 1RM',
    muscleDistribution: 'Muscle distribution',
    noPRs: 'No records yet',
    customizeStats: 'Customize',
    doneEditing: 'Done',
    statsBlock_tiles: 'Workout summary',
    statsBlock_streakCalendar: 'Streak calendar',
    statsBlock_steps: 'Steps',
    progress: 'Progress',
    noSessionsYet: 'No workouts logged yet.',
    noStatsEnabled: 'No stats enabled — tap Customize to turn blocks on',
    muscleFatigue: 'Muscle fatigue',
    fatigueLevel_fatigued: 'Fatigued',
    fatigueLevel_recovering: 'Recovering',
    fatigueLevel_fresh: 'Fresh',
    fatigueLevel_none: 'No data',
    daysAgo: '{n}d ago',

    // Measures page
    measureValuePlaceholder: 'Value',
    saveMeasure: 'Save',
    noMeasures: 'No measurements logged',
    progression: 'Progression',
    measureInvalidValue: 'Invalid value',
    measureSaveFailed: 'Could not save',
    // Custom measure types
    measureAddType: 'New measurement',
    measureAddTypeAria: 'Add body part',
    measureAddTypePill: '+ Add',
    measureTypeGroupLabel: 'Group',
    measureTypeNewGroup: 'Create a new group',
    measureTypeNewGroupName: 'Group name',
    measureTypeNameLabel: 'Body part',
    measureTypeNamePlaceholder: 'e.g. Left calf',
    measureTypeNameRequired: 'Give the body part a name.',
    measureTypeDuplicate: 'A measurement with that name already exists.',
    measureTypeGroupRequired: 'Give the group a name.',
    measureTypeUnitLabel: 'Unit',
    measureTypeUnitOther: 'Other',
    measureTypeUnitPlaceholder: 'e.g. bpm',
    measureTypeUnitRequired: 'Give the unit a name.',
    measureTypeYours: 'Your measurements',
    deleteMeasureTypeTitle: 'Delete this measurement?',
    deleteMeasureTypeMessage: 'The values already logged under it are deleted too.',
    measureGroup_general: 'General',
    measureGroup_torso: 'Torso',
    measureGroup_arms: 'Arms',
    measureGroup_legs: 'Legs',
    measureType_weight: 'Weight',
    measureType_height: 'Height',
    measureType_bodyFat: 'Body fat %',
    measureType_chest: 'Chest',
    measureType_waist: 'Waist',
    measureType_hips: 'Hips',
    measureType_neck: 'Neck',
    measureType_shoulders: 'Shoulders',
    measureType_biceps: 'Biceps',
    measureType_forearm: 'Forearm',
    measureType_quadriceps: 'Quadriceps',
    measureType_calves: 'Calves',

    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    accentColor: 'Main color',
    colorGreen: 'Green',
    colorBlue: 'Blue',
    colorPurple: 'Purple',
    colorPink: 'Pink',
    colorRed: 'Red',
    colorOrange: 'Orange',
    fontSize: 'Text size',
    fontSizeSmall: 'Small',
    fontSizeMedium: 'Medium',
    fontSizeLarge: 'Large',
    fontSizeExtraLarge: 'Extra large',
    sound: 'Sound',
    soundToggle: 'App sounds',
    language: 'Language',
    langPt: 'Português',
    langEn: 'English',

    settingsTitle: 'Settings',
    settingsSections: 'Sections',
    settingsSectionsDesc: 'Choose which parts of the app show up in navigation.',
    sectionGym: 'Workout',
    dataSection: 'Your data',
    dataSectionDesc: 'Save a full copy or just your workouts, and bring data back in.',
    exportData: 'Save a copy',
    exportDataDesc: 'Choose what to save',
    exportChoiceQuestion: 'What do you want to save?',
    exportChoiceFull: 'Full backup (JSON)',
    exportChoiceFullDesc: 'Everything: workouts, plans, measurements, nutrition and settings',
    exportCsv: 'Workouts only (CSV)',
    exportCsvDesc: 'One row per set, for Excel or another app',
    importCsv: 'Import',
    importCsvDesc: 'From a BeefUp copy or another app',
    importChoiceQuestion: 'Where is the file from?',
    importSourceBeefUp: 'A BeefUp copy (CSV)',
    importSourceBeefUpDesc: 'Restores your workouts exactly, without duplicates',
    importSourceOther: 'Another app (CSV)',
    importSourceOtherDesc: 'Strong, Hevy and the like — exercises are matched by name',
    importSourceJson: 'Full backup (JSON)',
    importSourceJsonDesc: 'Restores everything — replaces your current data',
    importBackupTitle: 'Restore backup?',
    importBackupWarn: "This erases your current data and puts the file's data in its place. It can't be undone.",
    restore: 'Restore',
    importDone: 'Imported {w} workouts and {s} sets.',
    importFailed: "Couldn't complete that. Try again.",
    unmatchedExercises: '{n} exercises were not recognised and kept their original name.',
    csvNotBeefUp: 'That file is not a BeefUp copy. Try the "Another app" option.',
    csvNoColumns: "Couldn't find exercise, date and set columns in this CSV.",

    // Nutrition
    nutrition: 'Nutrition',
    calories: 'Calories',
    kcal: 'kcal',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    fiber: 'Fiber',
    sugar: 'Sugar',
    saturatedFat: 'Saturated fat',
    transFat: 'Trans fat',
    sodium: 'Sodium',
    potassium: 'Potassium',
    calcium: 'Calcium',
    iron: 'Iron',
    moreDetails: 'More details',
    noData: 'no data',
    searchingFood: 'Searching...',
    typeToSearch: 'Type to search foods',
    foodSearchFailed: 'Search failed. Check your connection.',
    foodSearchLimit: 'Too many searches. Wait {n}s.',
    retry: 'Try again',
    goal: 'Goal',
    water: 'Water',
    addWater: 'Add glass',
    meals: 'Meals',
    breakfast: 'Breakfast',
    morningSnack: 'Morning snack',
    lunch: 'Lunch',
    afternoonSnack: 'Afternoon snack',
    dinner: 'Dinner',
    snack: 'Snack',
    newMeal: 'New meal',
    mealName: 'Meal name',
    deleteMealTitle: 'Delete meal?',
    deleteMealConfirm: 'This removes "{name}" from the list. Already-logged entries stay.',
    addFood: 'Add food',
    searchFood: 'Search foods...',
    searchOnline: 'Search brands online',
    insaCredit: 'Fonte: Base de Dados da Composição de Alimentos. Instituto Nacional de Saúde Doutor Ricardo Jorge, I. P. - INSA. v 7.1 - 2026',
    scanBarcode: 'Scan barcode',
    scanPreparingCamera: 'Preparing camera...',
    scanAimAtBarcode: 'Point the camera at the barcode',
    scanProductNotFound: 'Product not found.',
    scanTryAgain: 'Try again',
    scanCameraDenied: 'No camera access. Allow it in your browser settings.',
    scanNoCamera: 'No camera found.',
    serving: 'Serving',
    grams: 'Grams',
    units: 'Units',
    quantity: 'Quantity',
    customFood: 'Custom food',
    foodName: 'Food name',
    add: 'Add',
    editGoals: 'Edit goals',
    editMealsList: 'Edit meals',
    nutritionGoals: 'Nutrition goals',
    calculator: 'Calculator',
    manual: 'Manual',
    age: 'Age',
    height: 'Height (cm)',
    bodyWeight: 'Weight (kg)',
    sex: 'Sex',
    male: 'Male',
    female: 'Female',
    activity: 'Activity',
    actSedentary: 'Sedentary',
    actLight: 'Light',
    actModerate: 'Moderate',
    actActive: 'Active',
    actVeryActive: 'Very active',
    actFromWorkout: 'From workout data',
    objCut: 'Cut',
    objMaintain: 'Maintain',
    objBulk: 'Bulk',
    calculate: 'Calculate',
    glasses: 'glasses',
    proteinShort: 'P',
    carbsShort: 'C',
    fatShort: 'F',
    deleteFoodTitle: 'Delete entry?',
    deleteFoodConfirm: 'This removes "{name}" from today.',
    deleteCustomFoodTitle: 'Delete food?',
    deleteCustomFoodConfirm: 'This removes "{name}" from your custom foods.',
    deleteCustomExerciseTitle: 'Delete exercise?',
    deleteCustomExerciseConfirm: 'This removes "{name}" from your custom exercises.',
    macrosFromGoal: 'Macros add up to {kcal} kcal',
    favouriteFood: 'Mark as favourite',

    // Onboarding
    obWelcome: 'BeefUp',
    obWelcomeSub: 'How do you want to use the app?',
    obStart: 'Start',
    obStartDesc: 'Train and track yourself',
    obHelping: 'I am helping others',
    obHelpingDesc: 'Manage clients as a coach',
    obFocusTitle: 'What will you use the app for?',
    obFocusGym: 'Gym',
    obFocusGymDesc: 'Plans and workouts',
    obFocusNutrition: 'Nutrition',
    obFocusNutritionDesc: 'Calories and macros',
    obFocusBoth: 'Both',
    obFocusBothDesc: 'Training and diet together',
    obMeasuresTitle: 'Your measurements',
    obMeasuresSub: 'Optional, skip any field',
    obGoalsTitle: 'Your goal',
    obNext: 'Next',
    obSkip: 'Skip',
    obFinish: 'Finish',
    obHelperCreateAccount: 'Create your trainer account',
    obHelperSignIn: 'Sign in to your trainer account',
    obHelperAccountWhy: 'You need an account so your clients can link to you and their data can reach you.',
    obHelperContinue: 'Continue',
    obHelperAccountFailed: "Couldn't continue. Check the details.",
    obHelperConfirmEmail: 'Account created. Confirm your email before continuing (check your inbox).',
    // Explainers
    obExpGymTitle: 'Workouts always with you',
    obExpGymBody: 'Build plans, log sets, and watch your progression over time.',
    obExpNutritionTitle: 'Nutrition made simple',
    obExpNutritionBody: 'Track calories, macros and water with goals calculated for you.',
    obExpMeasuresTitle: 'See your progress',
    obExpMeasuresBody: 'Logging measurements helps you see real results, not just the scale.',
    obExpGoalsTitle: 'All set',
    obExpGoalsBody: 'Your nutrition goals are ready. Let’s get started!',
    obLoadPlanTitle: 'Pre-made plan?',
    obLoadPlanSub: 'Start right away with a plan, or build your own from scratch.',
    obLoadPlanYes: 'Yes, load Push Pull Legs',
    obLoadPlanYesDesc: '3 workouts and a weekly plan ready to use',
    obLoadPlanNo: 'No, I\'ll start from scratch',
    obLoadPlanNoDesc: 'I\'ll build my own workouts and plan',

    // Coach dashboard
    dashCalendar: 'Calendar',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    dashClients: 'Clients',
    dashInviteClient: 'Invite student',
    dashNoClients: "You don't have any linked students yet.",
    dashSelectClient: 'Pick a student on the left.',
    dashNotes: 'Notes',
    dashNotesPlaceholder: 'Write a note about the client...',
    dashAssign: 'Assign',
    dashApptType: 'Type',
    dashApptConsulta: 'Consultation',
    dashApptTreino: 'Training',
    dashApptRotina: 'Routine',
    dashSelectTimeTitle: 'Select time',
    dashTimeOk: 'OK',
    dashTimeKeyboardToggle: 'Enter time manually',
    dashUpcoming: 'Upcoming',
    dashFilterAll: 'All',
    dashNoUpcoming: 'No upcoming appointments.',
    dashUnassigned: 'Nothing scheduled',
    dashGym: 'Gym',
    dashMeasures: 'Measures',
    dashMeasuresLogTab: 'Log',
    dashMeasuresGoalsTab: 'Goals',
    dashMeasureGoalsDesc: "Goals you set appear in the client's app; they can't change them.",
    dashMeasureGoalDefine: '+ Set goal',
    dashMeasureGoalPlaceholder: 'Target value',
    deleteMeasureGoalTitle: 'Remove this goal?',
    dashNoMeasureGoals: "You haven't set any goals for this client yet.",
    dashMeasureGoalNoData: 'Log a value to see progress.',
    dashMeasureGoalReached: 'Reached',
    dashMeasureGoalsMore: '+{n} goals',
    dashOverview: 'Overview',
    dashTime: 'Time',
    dashSync: 'Sync',
    // Trainer account and invite codes
    dashAccount: 'Account',
    dashSyncUnavailable: 'Sync not available.',
    dashSignIn: 'Sign in',
    dashSignUp: 'Create account',
    dashDisplayName: 'Display name',
    dashEmail: 'Email',
    dashPassword: 'Password',
    dashNeedAccount: "Don't have an account? Create one",
    dashHaveAccount: 'Already have an account? Sign in',
    dashConnected: 'Connected',
    dashSignOut: 'Sign out',
    dashInvites: 'Invites',
    dashInvitesDesc: "Generate an invite and send your client the link. The link is what connects them to you — the code alone won't do, it's only here to identify and revoke the invite.",
    dashNewInvite: 'New invite',
    dashNoInvites: 'No active invites',
    dashCopyInviteLink: 'Copy invite link',
    dashCopyLink: 'Copy link',
    dashCopied: 'Copied!',
    dashInviteCodeLabel: 'code',
    dashInviteLinkUnavailable: "Couldn't create the link (missing configuration).",
    dashRevoke: 'Revoke',
    dashRevokeInviteTitle: 'Revoke this code?',
    dashLinked: 'Linked',
    dashSessions: 'Sessions',
    dashNutrition: 'Nutrition',
    dashNothingShared: "The client hasn't shared any data yet.",
    // Prescribing workouts and unlinking a client
    dashPrescribeDesc: "Workouts you prescribe show up in the client's app and they can't change them.",
    dashNoWorkouts: "This client has no workouts yet.",
    dashPrescribeWorkout: '+ Prescribe workout',
    dashPrescribedByYou: 'prescribed by you',
    dashClientOwn: "student's own",
    dashUnprescribeTitle: 'Remove "{name}"?',
    dashUnprescribeMessage: "The workout disappears from the client's app on their next sync. Workouts they already logged are not affected.",
    dashPrescribePlanDesc: "The weekly plan you build shows up in the client's app; they pick it as their active plan.",
    dashNoPlan: "You haven't assigned a plan to this client yet.",
    dashPrescribePlan: '+ Create plan',
    dashUnprescribePlanTitle: 'Remove the plan?',
    dashUnprescribePlanMessage: "The plan disappears from the client's app on their next sync.",
    dashPrescribeGoalsDesc: "The goals you set show up in the client's app; they can't change them while active.",
    dashNoGoals: "You haven't set nutrition goals for this client yet.",
    dashPrescribeGoals: '+ Set goals',
    dashUnprescribeGoalsTitle: 'Remove the goals?',
    dashUnprescribeGoalsMessage: "The goals disappear from the client's app on their next sync; they fall back to their own.",
    dashNoNutritionData: "This client hasn't logged any meals yet.",
    dashPrevDay: 'Previous day',
    dashNextDay: 'Next day',
    dashPlanTab: 'Plan',
    dashDailyData: 'Daily data',
    dashScopeNotShared: "Your student hasn't shared this part with you yet. They can turn it on in their app settings.",
    dashSearchClients: 'Search student',
    dashNoSessions: "This student hasn't logged any workouts yet.",
    dashNoMeals: 'Nothing logged on this day.',
    dashLastSession: 'last on',
    dashNoAppointment: 'No appointment scheduled.',
    dashNoNotes: "You haven't written any notes about this student yet.",
    micronutrients: 'Micronutrients',
    dashUnlinkClient: 'Unlink student',
    dashUnlinkClientTitle: 'Unlink {name}?',
    dashUnlinkClientMessage: "You'll stop seeing this client's data. Their data isn't deleted, and they can link again with a new code.",
    // Student linking to a trainer
    trainerSectionTitle: 'Personal Trainer',
    trainerUnavailable: "Linking to a trainer isn't available in this build.",
    trainerLinkExplain: 'Your trainer will be able to see what you choose to share, and an account will be created for you.',
    trainerLinkButton: 'Link to a trainer',
    trainerSyncStatusOff: 'Sync off',
    trainerSyncStatusIdle: 'Synced',
    trainerSyncStatusSyncing: 'Syncing…',
    trainerSyncStatusOffline: 'Offline',
    trainerSyncStatusError: 'Sync error',
    trainerLastSyncedAt: 'Last synced: {time}',
    trainerNeverSynced: 'Not synced yet',
    trainerSyncNowLabel: 'Sync now',
    trainerShareSectionTitle: 'What you share',
    trainerScopesNote: 'You can change this any time.',
    trainerScopeUpdateFailed: "Couldn't update. Try again.",
    trainerUnlinkButton: 'Unlink from trainer',
    trainerUnlinkTitle: 'Unlink from trainer?',
    trainerUnlinkMessage: 'Your trainer will no longer be able to see your data. Data already saved in this app is not deleted, and your login account stays created.',
    trainerUnlinkFailed: "Couldn't unlink. Try again.",
    trainerLinkStep: 'Step {n} of {total}',
    trainerLinkNeedsInvite: "You need an invite link from your trainer to link up. A code alone isn't enough any more — ask them to send you the link.",
    trainerLinkScopesTitle: "What you'll share",
    trainerLinkScopesExplain: 'Choose what your trainer will be able to see. You can change this any time.',
    trainerLinkConnectExplain: 'This invite connects you to the following server. Confirm before continuing.',
    trainerLinkConnectHostLabel: 'Server',
    trainerLinkConnectSchemaMissing: "This server isn't set up to accept connections yet. Let your trainer know.",
    trainerLinkConnectUnreachable: "Couldn't reach this server. Check your connection and try again.",
    trainerLinkConnectUnknown: "Couldn't confirm this server. Try again.",
    trainerLinkConnectInvalidLink: "This link doesn't look valid. Ask your trainer for a new one.",
    trainerLinkAccountExplain: 'We need to create an account so your data can reach your trainer.',
    trainerLinkSignInExplain: 'Sign in with the account you already use with this trainer.',
    trainerLinkHaveAccount: 'I already have an account — sign in',
    trainerLinkNeedAccount: "I don't have an account — sign up",
    trainerLinkEmailLabel: 'Email',
    trainerLinkPasswordLabel: 'Password',
    trainerLinkConfirmExplain: 'Confirm the details before linking.',
    trainerLinkScopesNone: 'Nothing selected',
    trainerLinkNext: 'Next',
    trainerLinkSuccessTitle: 'Linked to {name}',
    trainerLinkSuccessDesc: 'From now on, your trainer sees what you chose to share.',
    trainerLinkScopesPending: "Linked, but your sharing choices weren't saved. You aren't sharing anything yet — set it in Settings.",
    trainerSetupIntroTitle: 'Your own Supabase project',
    trainerSetupIntroBody: "Every trainer creates and controls their own Supabase project — that's where your clients' data lives, not on our servers. Let's create and connect yours in a few steps.",
    trainerSetupProjectTitle: 'Create a project',
    trainerSetupProjectBody: "Open Supabase, sign up if you haven't already, and create a new (free) project. It can take a minute or two to provision — come back here once it's ready.",
    trainerSetupProjectLink: 'Open supabase.com',
    trainerSetupSqlTitle: 'Set up the database',
    trainerSetupSqlBody: 'In your project, open the SQL editor, paste the script below, and run it. This creates the tables and rules the app needs.',
    trainerSetupCopySql: 'Copy SQL script',
    trainerSetupSqlCopyFailed: "Couldn't copy. Try selecting and copying it manually.",
    trainerSetupSqlEditorLink: 'Open SQL editor',
    trainerSetupCredentialsTitle: 'Connect your project',
    trainerSetupCredentialsBody: 'In your project, go to Settings > API and paste the URL and the "anon public" key here.',
    trainerSetupUrlLabel: 'Project URL',
    trainerSetupKeyLabel: 'Anon key',
    trainerSetupConnectButton: 'Test and connect',
    trainerSetupInvalidConfig: "This doesn't look like a valid Supabase project URL or key.",
    trainerSetupSchemaMissing: "This project hasn't had the SQL script run yet. Copy it and run it in your project's SQL editor.",
    trainerSetupUnreachable: "Couldn't reach this project. Check your connection and the URL.",
    trainerSetupTestUnknown: "Couldn't confirm this project. Try again.",
    trainerSetupTrainerTaken: 'This project already has a trainer linked to it. Use the original account or create another project.',
    prescribedBadge: 'prescribed by your trainer',
    prescribedLocked: 'Prescribed by your trainer, not editable',
    // Moved out of inline lang ternaries
    advanced: "Advanced",
    bodyBack: "Back",
    bodyFront: "Front",
    choose: "Choose",
    copySuffix: "copy",
    createNewWorkout: "+ Create new workout",
    currentPlan: "Current Plan",
    currentStreak: "Current streak",
    currentStreakShort: "Current streak",
    bestStreakLabel: "Best: {n} days",
    daysTitle: "Days",
    toggleDayType: "Toggle day type",
    deleteWorkoutAction: "Delete",
    demoPresetTitle: "Load example",
    demoPresetDesc: "Example plan and workouts (Push Pull Legs)",
    demoPresetLoaded: "Example loaded.",
    duplicate: "Duplicate",
    edit: "Edit",
    load: "Load",
    loading: "Loading",
    myWorkouts: "My Workouts",
    newPersonalRecord: "New personal record!",
    noActivePlanTap: "No active plan — tap to create",
    noExercises: "No exercises.",
    noExercisesYet: "No exercises yet.",
    noWorkoutsThisWeek: "No workouts logged this week yet.",
    rename: "Rename",
    renameWorkoutPrompt: "New workout name:",
    deleteWorkoutTitle: 'Delete "{name}"?',
    cannotUndo: "This action cannot be undone.",
    deletePlanTitle: 'Delete "{name}"?',
    deleteMeasureTitle: "Delete measurement?",
    deleteNoteTitle: "Delete note?",
    deletePlanDayTitle: "Remove this day from the plan?",
    deleteAppointmentTitle: "Delete appointment?",
    removeExerciseTitle: "Remove exercise?",
    removeExerciseConfirm: "This removes the exercise and every set logged under it, for this workout.",
    restDayBody: "Recover and come back stronger.",
    setSingular: "Set",
    share: "Share",
    startWorkoutAria: "Start workout",
    valuesPer100g: "Values per 100 g",
    weekMuscles: "This week's muscles",
    pwaInstallTitle: 'Install BeefUp',
    pwaInstallDesc: 'Add the app to your device and use it offline.',
    pwaInstall: 'Install',
    pwaInstallIosDesc: 'Tap Share, then "Add to Home Screen".',
    pwaUpdateTitle: 'New version available',
    pwaUpdateDesc: 'Reload to update the app.',
    pwaUpdate: 'Update',
    pwaOfflineReady: 'App ready to work offline.',
    pwaDismiss: 'Not now',

  },
}

export default strings
