const strings = {
  pt: {
    // Nav
    history: 'Histórico',
    settings: 'Definições',
    profile: 'Perfil',

    // Home
    today: 'Hoje',
      homeTitle: 'Treino',
    restDay: 'Dia de Descanso',
    startWorkout: 'Iniciar',
    startAnother: 'Outro treino',
    manageWorkouts: 'Gerir treinos',
    streak: 'Série',
    days: 'dias',
    steps: 'Passos',
    registerSteps: 'Registar passos de hoje',
    personalBests: 'Recordes pessoais',
    editPBs: 'Editar',
    noWorkoutScheduled: 'Sem treino agendado',
    noPlan: 'Sem plano ativo',
    choosePlan: 'Escolher plano',

    // Active workout
    end: 'Terminar',
    cancel: 'Cancelar',
    endWorkout: 'Terminar treino',
    cancelWorkout: 'Cancelar treino',
    endConfirm: 'Queres terminar este treino?',
    cancelConfirm: 'Queres cancelar? O progresso será perdido.',
    addSet: 'Série',
    addExercise: 'Exercício',
    removeSet: 'Remover série',
    removeExercise: 'Remover exercício',
    reps: 'Reps',
    weight: 'Peso (kg)',
    notesPlaceholder: 'Adicionar notas...',
    done: 'Feito',
    rest: 'Descanso',
    restTimer: 'Temporizador de descanso',
    restTimerDone: 'Descanso terminado!',
    startRest: 'Iniciar',
    skipRest: 'Saltar',
    oneRM: 'Calcular 1RM',
    oneRMResult: '1RM estimado',
    workoutDone: 'Treino concluído!',
    totalTime: 'Tempo total',
    totalSets: 'Séries totais',
    totalVolume: 'Volume total',
    great: 'Ótimo trabalho!',
    close: 'Fechar',
    seconds: 's',
    minutes: 'min',

    // Exercises modal
    searchExercises: 'Pesquisar exercícios...',
    allTags: 'Todos',
    favourites: 'Favoritos',
    noResults: 'Sem resultados',

    // History
    noHistory: 'Sem histórico ainda',
    historyEmpty: 'Completa um treino para começar.',
    volume: 'volume',
    sets: 'séries',
    exercises: 'exercícios',

    // Plan settings
    plans: 'Planos',
    newPlan: 'Novo plano',
    activePlan: 'Plano ativo',
    setActive: 'Definir como ativo',
    editPlan: 'Editar plano',
    editWorkout: 'Editar treino',
    deletePlan: 'Eliminar plano',
    planName: 'Nome do plano',
    addDay: 'Dia',
    workoutDay: 'Treino',
    dayRest: 'Descanso',
    selectWorkout: 'Selecionar treino',
    workouts: 'Treinos',
    newWorkout: 'Novo treino',
    workoutName: 'Nome do treino',
    save: 'Guardar',
    delete: 'Eliminar',
    back: 'Voltar',
    confirm: 'Confirmar',

    // Steps modal
    stepsToday: 'Passos de hoje',
    stepsPlaceholder: 'ex. 8500',
    saveSteps: 'Guardar',

    // PB edit modal
    choosePBs: 'Escolher recordes a mostrar',
    pbSteps: 'Passos diários',

    // Profile
    profileTitle: 'Perfil',
    statistics: 'Estatísticas',
    measures: 'Medidas',
    previousWorkouts: 'Treinos anteriores',
    duration: 'Duração',
    weeklyProgress: 'Progresso semanal',

    // Statistics page
    daysTrained: 'Dias treinados',
    totalSessions: 'Treinos totais',
    totalReps: 'Reps totais',

    // Measures page
    measureValuePlaceholder: 'Valor',
    saveMeasure: 'Guardar',
    noMeasures: 'Sem medidas registadas',
    progression: 'Progressão',
    measureType_weight: 'Peso',
    measureType_height: 'Altura',
    measureType_chest: 'Peito',
    measureType_arms: 'Braços',
    measureType_legs: 'Pernas',
    measureType_belly: 'Barriga',

    // Themes / lang
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
    language: 'Idioma',
    langPt: 'Português',
    langEn: 'English',

    // Settings
    settingsTitle: 'Definições',
    healthConnect: 'Health Connect',
    healthConnectDesc: 'Sincronizar passos com Health Connect',
    connect: 'Ligar',
    disconnect: 'Desligar',
    connected: 'Ligado',

    // Nutrition
    nutrition: 'Nutrição',
    calories: 'Calorias',
    kcal: 'kcal',
    protein: 'Proteína',
    carbs: 'Hidratos',
    fat: 'Gordura',
    remaining: 'Restante',
    consumed: 'Consumido',
    goal: 'Objetivo',
    water: 'Água',
    addWater: 'Adicionar copo',
    breakfast: 'Pequeno-almoço',
    lunch: 'Almoço',
    dinner: 'Jantar',
    snack: 'Lanche',
    addFood: 'Adicionar alimento',
    searchFood: 'Pesquisar alimentos...',
    serving: 'Porção',
    grams: 'g',
    quantity: 'Quantidade',
    customFood: 'Alimento personalizado',
    foodName: 'Nome do alimento',
    add: 'Adicionar',
    editGoals: 'Editar objetivos',
    nutritionGoals: 'Objetivos nutricionais',
    calculator: 'Calculadora',
    manual: 'Manual',
    age: 'Idade',
    height: 'Altura (cm)',
    bodyWeight: 'Peso (kg)',
    sex: 'Sexo',
    male: 'Masculino',
    female: 'Feminino',
    activity: 'Atividade',
    actSedentary: 'Sedentário',
    actLight: 'Leve',
    actModerate: 'Moderado',
    actActive: 'Ativo',
    actVeryActive: 'Muito ativo',
    actFromWorkout: 'Obter dos treinos',
    objective: 'Meta',
    objCut: 'Perder',
    objMaintain: 'Manter',
    objBulk: 'Ganhar',
    calculate: 'Calcular',
    noFoodToday: 'Nada registado hoje',
    glasses: 'copos',

    // Onboarding
    obWelcome: 'BeefUp',
    obWelcomeSub: 'Como queres usar a app?',
    obStart: 'Começar',
    obStartDesc: 'Treina e acompanha-te a ti próprio',
    obHelping: 'Estou a ajudar outros',
    obHelpingDesc: 'Gere clientes como treinador',
    obFocusTitle: 'Para que vais usar a app?',
    obFocusGym: 'Ginásio',
    obFocusGymDesc: 'Planos e treinos',
    obFocusNutrition: 'Nutrição',
    obFocusNutritionDesc: 'Calorias e macros',
    obFocusBoth: 'Ambos',
    obFocusBothDesc: 'Treino e dieta juntos',
    obMeasuresTitle: 'As tuas medidas',
    obMeasuresSub: 'Opcional, podes saltar qualquer campo',
    obGoalsTitle: 'O teu objetivo',
    obNext: 'Seguinte',
    obSkip: 'Saltar',
    obFinish: 'Concluir',
    obDesktopOnly: 'O painel de treinador está disponível apenas no computador.',
    // Explainers
    obExpGymTitle: 'Treinos sempre contigo',
    obExpGymBody: 'Cria planos, regista séries e vê a tua progressão ao longo do tempo.',
    obExpNutritionTitle: 'Nutrição simples',
    obExpNutritionBody: 'Acompanha calorias, macros e água com objetivos calculados para ti.',
    obExpMeasuresTitle: 'Vê o teu progresso',
    obExpMeasuresBody: 'Registar medidas ajuda-te a ver resultados reais, não só na balança.',
    obExpGoalsTitle: 'Tudo definido',
    obExpGoalsBody: 'Os teus objetivos nutricionais estão prontos. Vamos começar!',
    resetOnboarding: 'Recomeçar configuração',

    // Coach dashboard
    dashCalendar: 'Calendário',
    dashClients: 'Clientes',
    dashNewClient: 'Novo cliente',
    dashClientName: 'Nome',
    dashClientInfo: 'Informação',
    dashCreate: 'Criar',
    dashNoClients: 'Sem clientes ainda',
    dashSelectClient: 'Seleciona um cliente',
    dashNotes: 'Notas',
    dashNotesPlaceholder: 'Escrever nota sobre o cliente...',
    dashAssign: 'Atribuir',
    dashUnassigned: 'Sem nada agendado',
    dashGym: 'Ginásio',
    dashNutrition: 'Nutrição',
    dashMeasures: 'Medidas',
    dashDelete: 'Eliminar cliente',
    dashOverview: 'Resumo',
    dashTime: 'Hora',
    dashSync: 'Sincronizar',
    dashSyncSetup: 'Configuração Firebase',
    dashSyncDesc: 'Cola o objeto firebaseConfig do teu projeto Firebase. Os dados ficam no teu Firestore, extraímos só o necessário.',
    dashConfigSaved: 'Configuração guardada.',
    dashPush: 'Enviar clientes',
    dashPull: 'Obter clientes',
    dashPushed: 'Enviado',
    dashPulled: 'Obtido',
  },

  en: {
    history: 'History',
    settings: 'Settings',
    profile: 'Profile',

    today: 'Today',
      homeTitle: 'Workout',
    restDay: 'Rest Day',
    startWorkout: 'Start',
    startAnother: 'Another workout',
    manageWorkouts: 'Manage workouts',
    streak: 'Streak',
    days: 'days',
    steps: 'Steps',
    registerSteps: "Register today's steps",
    personalBests: 'Personal Bests',
    editPBs: 'Edit',
    noWorkoutScheduled: 'No workout scheduled',
    noPlan: 'No active plan',
    choosePlan: 'Choose plan',

    end: 'End',
    cancel: 'Cancel',
    endWorkout: 'End Workout',
    cancelWorkout: 'Cancel Workout',
    endConfirm: 'End this workout?',
    cancelConfirm: 'Cancel? All progress will be lost.',
    addSet: 'Set',
    addExercise: 'Exercise',
    removeSet: 'Remove set',
    removeExercise: 'Remove exercise',
    reps: 'Reps',
    weight: 'Weight (kg)',
    notesPlaceholder: 'Add notes...',
    done: 'Done',
    rest: 'Rest',
    restTimer: 'Rest timer',
    restTimerDone: 'Rest over!',
    startRest: 'Start',
    skipRest: 'Skip',
    oneRM: 'Calculate 1RM',
    oneRMResult: 'Estimated 1RM',
    workoutDone: 'Workout complete!',
    totalTime: 'Total time',
    totalSets: 'Total sets',
    totalVolume: 'Total volume',
    great: 'Great work!',
    close: 'Close',
    seconds: 's',
    minutes: 'min',

    searchExercises: 'Search exercises...',
    allTags: 'All',
    favourites: 'Favourites',
    noResults: 'No results',

    noHistory: 'No history yet',
    historyEmpty: 'Complete a workout to get started.',
    volume: 'volume',
    sets: 'sets',
    exercises: 'exercises',

    plans: 'Plans',
    newPlan: 'New plan',
    activePlan: 'Active plan',
    setActive: 'Set as active',
    editPlan: 'Edit plan',
    editWorkout: 'Edit workout',
    deletePlan: 'Delete plan',
    planName: 'Plan name',
    addDay: 'Day',
    workoutDay: 'Workout',
    dayRest: 'Rest',
    selectWorkout: 'Select workout',
    workouts: 'Workouts',
    newWorkout: 'New workout',
    workoutName: 'Workout name',
    save: 'Save',
    delete: 'Delete',
    back: 'Back',
    confirm: 'Confirm',

    stepsToday: "Today's steps",
    stepsPlaceholder: 'e.g. 8500',
    saveSteps: 'Save',

    choosePBs: 'Choose records to display',
    pbSteps: 'Daily steps',

    // Profile
    profileTitle: 'Profile',
    statistics: 'Statistics',
    measures: 'Measures',
    previousWorkouts: 'Previous workouts',
    duration: 'Duration',
    weeklyProgress: 'Weekly progress',

    // Statistics page
    daysTrained: 'Days trained',
    totalSessions: 'Total sessions',
    totalReps: 'Total reps',

    // Measures page
    measureValuePlaceholder: 'Value',
    saveMeasure: 'Save',
    noMeasures: 'No measurements logged',
    progression: 'Progression',
    measureType_weight: 'Weight',
    measureType_height: 'Height',
    measureType_chest: 'Chest',
    measureType_arms: 'Arms',
    measureType_legs: 'Legs',
    measureType_belly: 'Belly',

    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    language: 'Language',
    langPt: 'Português',
    langEn: 'English',

    settingsTitle: 'Settings',
    healthConnect: 'Health Connect',
    healthConnectDesc: 'Sync steps with Health Connect',
    connect: 'Connect',
    disconnect: 'Disconnect',
    connected: 'Connected',

    // Nutrition
    nutrition: 'Nutrition',
    calories: 'Calories',
    kcal: 'kcal',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    remaining: 'Remaining',
    consumed: 'Consumed',
    goal: 'Goal',
    water: 'Water',
    addWater: 'Add glass',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    addFood: 'Add food',
    searchFood: 'Search foods...',
    serving: 'Serving',
    grams: 'g',
    quantity: 'Quantity',
    customFood: 'Custom food',
    foodName: 'Food name',
    add: 'Add',
    editGoals: 'Edit goals',
    nutritionGoals: 'Nutrition goals',
    calculator: 'Calculator',
    manual: 'Manual',
    age: 'Age',
    height: 'Height (cm)',
    bodyWeight: 'Weight (kg)',
    sex: 'Sex',
    male: 'Male',
    female: 'Female',
    activity: 'Activity',
    actSedentary: 'Sedentary',
    actLight: 'Light',
    actModerate: 'Moderate',
    actActive: 'Active',
    actVeryActive: 'Very active',
    actFromWorkout: 'From workout data',
    objective: 'Goal',
    objCut: 'Cut',
    objMaintain: 'Maintain',
    objBulk: 'Bulk',
    calculate: 'Calculate',
    noFoodToday: 'Nothing logged today',
    glasses: 'glasses',

    // Onboarding
    obWelcome: 'BeefUp',
    obWelcomeSub: 'How do you want to use the app?',
    obStart: 'Start',
    obStartDesc: 'Train and track yourself',
    obHelping: 'I am helping others',
    obHelpingDesc: 'Manage clients as a coach',
    obFocusTitle: 'What will you use the app for?',
    obFocusGym: 'Gym',
    obFocusGymDesc: 'Plans and workouts',
    obFocusNutrition: 'Nutrition',
    obFocusNutritionDesc: 'Calories and macros',
    obFocusBoth: 'Both',
    obFocusBothDesc: 'Training and diet together',
    obMeasuresTitle: 'Your measurements',
    obMeasuresSub: 'Optional, skip any field',
    obGoalsTitle: 'Your goal',
    obNext: 'Next',
    obSkip: 'Skip',
    obFinish: 'Finish',
    obDesktopOnly: 'The coach dashboard is available on desktop only.',
    // Explainers
    obExpGymTitle: 'Workouts always with you',
    obExpGymBody: 'Build plans, log sets, and watch your progression over time.',
    obExpNutritionTitle: 'Nutrition made simple',
    obExpNutritionBody: 'Track calories, macros and water with goals calculated for you.',
    obExpMeasuresTitle: 'See your progress',
    obExpMeasuresBody: 'Logging measurements helps you see real results, not just the scale.',
    obExpGoalsTitle: 'All set',
    obExpGoalsBody: 'Your nutrition goals are ready. Let’s get started!',
    resetOnboarding: 'Restart setup',

    // Coach dashboard
    dashCalendar: 'Calendar',
    dashClients: 'Clients',
    dashNewClient: 'New client',
    dashClientName: 'Name',
    dashClientInfo: 'Info',
    dashCreate: 'Create',
    dashNoClients: 'No clients yet',
    dashSelectClient: 'Select a client',
    dashNotes: 'Notes',
    dashNotesPlaceholder: 'Write a note about the client...',
    dashAssign: 'Assign',
    dashUnassigned: 'Nothing scheduled',
    dashGym: 'Gym',
    dashNutrition: 'Nutrition',
    dashMeasures: 'Measures',
    dashDelete: 'Delete client',
    dashOverview: 'Overview',
    dashTime: 'Time',
    dashSync: 'Sync',
    dashSyncSetup: 'Firebase setup',
    dashSyncDesc: 'Paste the firebaseConfig object from your Firebase project. Data lives in your own Firestore, we extract only what is needed.',
    dashConfigSaved: 'Config saved.',
    dashPush: 'Push clients',
    dashPull: 'Pull clients',
    dashPushed: 'Pushed',
    dashPulled: 'Pulled',
  },
}

export default strings
