const strings = {
  pt: {
    // Nav
    history: 'Histórico',
    settings: 'Definições',
    exercisesTitle: 'Exercícios',

    // Home
    homeTitle: 'Treino',
    restDay: 'Dia de Descanso',
    startWorkout: 'Iniciar',
    startAnother: 'Outro treino',
    days: 'dias',
    steps: 'Passos',
    noWorkoutScheduled: 'Sem treino agendado',
    noPlan: 'Sem plano ativo',
    choosePlan: 'Escolher plano',

    // Active workout
    end: 'Terminar',
    cancel: 'Cancelar',
    endWorkout: 'Terminar treino',
    cancelWorkout: 'Cancelar treino',
    minimize: 'Minimizar',
    endConfirm: 'Queres terminar este treino?',
    cancelConfirm: 'Queres cancelar? O progresso será perdido.',
    addExercise: 'Exercício',
    reps: 'Reps',
    weight: 'Peso (kg)',
    done: 'Concluído',
    rest: 'Descanso',
    restTimer: 'Temporizador de descanso',
    restTimerDone: 'Descanso terminado!',
    startRest: 'Iniciar',
    dragToAdjust: 'Arrasta para ajustar',
    skipRest: 'Saltar',
    oneRM: 'Calcular 1RM',
    oneRMResult: '1RM estimado',
    workoutDone: 'Treino concluído!',
    totalTime: 'Tempo total',
    totalSets: 'Séries totais',
    totalVolume: 'Volume total',
    great: 'Ótimo trabalho!',
    close: 'Fechar',
    seconds: 's',
    minutes: 'min',

    // Exercises modal
    searchExercises: 'Pesquisar exercícios...',
    allTags: 'Todos',
    noResults: 'Sem resultados',
    filters: 'Filtros',
    filterBodyPart: 'Parte do corpo',
    filterEquipment: 'Equipamento',
    rotateBody: 'Rodar',
    clearFilters: 'Limpar',
    applyFilters: 'Aplicar',
    noMediaYet: 'Vídeo em breve',
    instructions: 'Instruções',
    category: 'Categoria',
    primaryMuscle: 'Músculo principal',
    secondaryMusclesLabel: 'Músculos secundários',
    toggleCardView: 'Ver em cartões',
    toggleListView: 'Ver em lista',

    // History
    noHistory: 'Sem histórico ainda',
    historyEmpty: 'Completa um treino para começar.',
    volume: 'volume',
    sets: 'séries',
    exercises: 'exercícios',
    importWorkoutTitle: 'Importar treino?',
    importWorkout: 'Importar',
    setTypeNormal: 'Normal',
    setType_warmup: 'Aquecimento',
    setType_dropset: 'Dropset',
    setType_superset: 'Super-série',
    setType_failure: 'Falha',

    // Plan settings
    plans: 'Planos',
    newPlan: 'Novo plano',
    activePlan: 'Plano ativo',
    setActive: 'Definir como ativo',
    editPlan: 'Editar plano',
    editWorkout: 'Editar treino',
    planName: 'Nome do plano',
    workoutDay: 'Treino',
    dayRest: 'Descanso',
    selectWorkout: 'Selecionar treino',
    workouts: 'Treinos',
    newWorkout: 'Novo treino',
    workoutName: 'Nome do treino',
    exerciseNote: 'Nota',
    save: 'Guardar',
    delete: 'Eliminar',
    back: 'Voltar',
    confirm: 'Confirmar',

    // Steps modal
    stepsToday: 'Passos de hoje',
    stepsPlaceholder: 'ex. 8500',
    saveSteps: 'Guardar',


    // Profile
    profileTitle: 'Perfil',
    measures: 'Medidas',
    duration: 'Duração',
    weeklyProgress: 'Progresso semanal',

    // Statistics page
    daysTrained: 'Dias treinados',
    totalSessions: 'Treinos totais',
    totalReps: 'Reps totais',
    bestStreak: 'Melhor série',
    personalRecords: 'Recordes pessoais',
    personalRecordsLegend: '1RM estimado',
    muscleDistribution: 'Distribuição muscular',
    noPRs: 'Ainda sem recordes',
    customizeStats: 'Personalizar',
    doneEditing: 'Concluído',
    statsBlock_tiles: 'Resumo de treino',
    statsBlock_streakCalendar: 'Calendário de sequência',
    statsBlock_steps: 'Passos',
    nutritionTrend: 'Calorias ao longo do tempo',
    nutritionSummary: 'Resumo da nutrição',
    avgKcal: 'Média por dia',
    avgProtein: 'Proteína média',
    daysLogged: 'Dias registados',
    onTarget: 'No alvo',
    noNutritionData: 'Ainda sem refeições registadas. Regista comida uns dias e o teu histórico aparece aqui.',
    lastNDays: 'Últimos {n} dias',
    statsRange: 'Intervalo',
    custom: 'Personalizado',
    startDate: 'Data de início',
    apply: 'Aplicar',
    progress: 'Progresso',
    noSessionsInRange: 'Sem treinos neste período.',
    noStatsEnabled: 'Nenhuma estatística ativa — toca em Personalizar para ligar blocos',
    muscleFatigue: 'Fadiga muscular',
    fatigueLevel_fatigued: 'Fatigado',
    fatigueLevel_recovering: 'A recuperar',
    fatigueLevel_fresh: 'Fresco',
    fatigueLevel_none: 'Sem dados',
    daysAgo: 'há {n}d',

    // Measures page
    measureValuePlaceholder: 'Valor',
    saveMeasure: 'Guardar',
    noMeasures: 'Sem medidas registadas',
    progression: 'Progressão',
    measureInvalidValue: 'Valor inválido',
    measureSaveFailed: 'Não foi possível guardar',
    measureGroup_general: 'Geral',
    measureGroup_torso: 'Tronco',
    measureGroup_arms: 'Braços',
    measureGroup_legs: 'Pernas',
    measureType_weight: 'Peso',
    measureType_height: 'Altura',
    measureType_bodyFat: 'Massa gorda',
    measureType_chest: 'Peito',
    measureType_waist: 'Cintura',
    measureType_hips: 'Quadris',
    measureType_neck: 'Pescoço',
    measureType_shoulders: 'Ombros',
    measureType_biceps: 'Bíceps',
    measureType_forearm: 'Antebraço',
    measureType_quadriceps: 'Quadricípite',
    measureType_calves: 'Gémeos',

    // Themes / lang
    theme: 'Tema',
    themeLight: 'Claro',
    themeDark: 'Escuro',
    themeSystem: 'Sistema',
    accentColor: 'Cor principal',
    colorGreen: 'Verde',
    colorBlue: 'Azul',
    colorPurple: 'Roxo',
    colorPink: 'Rosa',
    colorRed: 'Vermelho',
    colorOrange: 'Laranja',
    language: 'Idioma',
    langPt: 'Português',
    langEn: 'English',

    // Settings
    settingsTitle: 'Definições',
    settingsSections: 'Secções',
    settingsSectionsDesc: 'Escolhe que partes da app aparecem na navegação.',
    sectionGym: 'Treino',
    dataSection: 'Os teus dados',
    dataSectionDesc: 'Guarda uma cópia completa ou só os treinos, e traz dados de volta.',
    exportData: 'Guardar cópia',
    exportDataDesc: 'Escolhe o que queres guardar',
    exportChoiceQuestion: 'O que queres guardar?',
    exportChoiceFull: 'Cópia completa (JSON)',
    exportChoiceFullDesc: 'Tudo: treinos, planos, medidas, nutrição e definições',
    exportCsv: 'Só os treinos (CSV)',
    exportCsvDesc: 'Uma linha por série, para o Excel ou outra app',
    importCsv: 'Importar',
    importCsvDesc: 'De uma cópia da BeefUp ou de outra app',
    importChoiceQuestion: 'De onde vem o ficheiro?',
    importSourceBeefUp: 'Cópia da BeefUp (CSV)',
    importSourceBeefUpDesc: 'Repõe os treinos tal e qual, sem duplicar',
    importSourceOther: 'Outra app (CSV)',
    importSourceOtherDesc: 'Strong, Hevy e afins — os exercícios são reconhecidos pelo nome',
    importSourceJson: 'Cópia completa (JSON)',
    importSourceJsonDesc: 'Restaura tudo — substitui os dados atuais',
    importBackupTitle: 'Restaurar cópia?',
    importBackupWarn: 'Isto apaga os dados atuais e põe no lugar os do ficheiro. Não dá para desfazer.',
    restore: 'Restaurar',
    importDone: 'Importados {w} treinos e {s} séries.',
    importFailed: 'Não foi possível concluir a operação. Tenta novamente.',
    unmatchedExercises: '{n} exercícios não reconhecidos ficaram com o nome original.',
    csvNotBeefUp: 'Este ficheiro não é uma cópia da BeefUp. Tenta a opção "Outra app".',
    csvNoColumns: 'Não encontrei as colunas de exercício, data e séries neste CSV.',

    // Nutrition
    nutrition: 'Nutrição',
    calories: 'Calorias',
    kcal: 'kcal',
    protein: 'Proteína',
    carbs: 'Hidratos',
    fat: 'Gordura',
    goal: 'Objetivo',
    water: 'Água',
    addWater: 'Adicionar copo',
    meals: 'Refeições',
    breakfast: 'Pequeno-almoço',
    morningSnack: 'Lanche da manhã',
    lunch: 'Almoço',
    afternoonSnack: 'Lanche da tarde',
    dinner: 'Jantar',
    snack: 'Lanche',
    newMeal: 'Nova refeição',
    mealName: 'Nome da refeição',
    deleteMealTitle: 'Eliminar refeição?',
    deleteMealConfirm: 'Isto elimina "{name}" da lista. Os registos já feitos não são apagados.',
    addFood: 'Adicionar alimento',
    searchFood: 'Pesquisar alimentos...',
    serving: 'Porção',
    grams: 'g',
    quantity: 'Quantidade',
    customFood: 'Alimento personalizado',
    foodName: 'Nome do alimento',
    add: 'Adicionar',
    editGoals: 'Editar objetivos',
    editMealsList: 'Editar refeições',
    nutritionGoals: 'Objetivos nutricionais',
    calculator: 'Calculadora',
    manual: 'Manual',
    age: 'Idade',
    height: 'Altura (cm)',
    bodyWeight: 'Peso (kg)',
    sex: 'Sexo',
    male: 'Masculino',
    female: 'Feminino',
    activity: 'Atividade',
    actSedentary: 'Sedentário',
    actLight: 'Leve',
    actModerate: 'Moderado',
    actActive: 'Ativo',
    actVeryActive: 'Muito ativo',
    actFromWorkout: 'Obter dos treinos',
    objCut: 'Perder',
    objMaintain: 'Manter',
    objBulk: 'Ganhar',
    calculate: 'Calcular',
    glasses: 'copos',
    proteinShort: 'P',
    carbsShort: 'H',
    fatShort: 'G',
    deleteFoodTitle: 'Eliminar registo?',
    deleteFoodConfirm: 'Isto elimina "{name}" do dia de hoje.',
    macrosFromGoal: 'Macros dão {kcal} kcal',
    favouriteFood: 'Marcar como favorito',

    // Onboarding
    obWelcome: 'BeefUp',
    obWelcomeSub: 'Como queres usar a app?',
    obStart: 'Começar',
    obStartDesc: 'Treina e acompanha-te a ti próprio',
    obHelping: 'Estou a ajudar outros',
    obHelpingDesc: 'Gere clientes como treinador',
    obFocusTitle: 'Para que vais usar a app?',
    obFocusGym: 'Ginásio',
    obFocusGymDesc: 'Planos e treinos',
    obFocusNutrition: 'Nutrição',
    obFocusNutritionDesc: 'Calorias e macros',
    obFocusBoth: 'Ambos',
    obFocusBothDesc: 'Treino e dieta juntos',
    unavailable: 'Indisponível',
    obMeasuresTitle: 'As tuas medidas',
    obMeasuresSub: 'Opcional, podes saltar qualquer campo',
    obGoalsTitle: 'O teu objetivo',
    obNext: 'Seguinte',
    obSkip: 'Saltar',
    obFinish: 'Concluir',
    obDesktopOnly: 'O painel de treinador está disponível apenas no computador.',
    // Explainers
    obExpGymTitle: 'Treinos sempre contigo',
    obExpGymBody: 'Cria planos, regista séries e vê a tua progressão ao longo do tempo.',
    obExpNutritionTitle: 'Nutrição simples',
    obExpNutritionBody: 'Acompanha calorias, macros e água com objetivos calculados para ti.',
    obExpMeasuresTitle: 'Vê o teu progresso',
    obExpMeasuresBody: 'Registar medidas ajuda-te a ver resultados reais, não só na balança.',
    obExpGoalsTitle: 'Tudo definido',
    obExpGoalsBody: 'Os teus objetivos nutricionais estão prontos. Vamos começar!',
    resetOnboarding: 'Recomeçar configuração',
    resetOnboardingWarn: 'Vais passar pela configuração inicial outra vez.',

    // Coach dashboard
    dashCalendar: 'Calendário',
    previousMonth: 'Mês anterior',
    nextMonth: 'Mês seguinte',
    dashClients: 'Clientes',
    dashNewClient: 'Novo cliente',
    dashClientName: 'Nome',
    dashClientInfo: 'Informação',
    dashCreate: 'Criar',
    dashNoClients: 'Sem clientes ainda',
    dashSelectClient: 'Seleciona um cliente',
    dashNotes: 'Notas',
    dashNotesPlaceholder: 'Escrever nota sobre o cliente...',
    dashAssign: 'Atribuir',
    dashUnassigned: 'Sem nada agendado',
    dashGym: 'Ginásio',
    dashMeasures: 'Medidas',
    dashDelete: 'Eliminar cliente',
    dashOverview: 'Resumo',
    dashTime: 'Hora',
    dashSync: 'Sincronizar',
    dashSyncSetup: 'Configuração Firebase',
    dashSyncDesc: 'Cola o objeto firebaseConfig do teu projeto Firebase. Os dados ficam no teu Firestore, extraímos só o necessário.',
    dashConfigSaved: 'Configuração guardada.',
    dashPush: 'Enviar clientes',
    dashPull: 'Obter clientes',
    dashPushed: 'Enviado',
    dashPulled: 'Obtido',
    // Moved out of inline lang ternaries
    advanced: "Avançado",
    bodyBack: "Costas",
    bodyFront: "Frente",
    choose: "Escolher",
    copySuffix: "cópia",
    createNewWorkout: "+ Criar novo treino",
    currentPlan: "Plano Atual",
    currentStreak: "Sequência atual",
    currentStreakShort: "Sequência atual",
    daysTitle: "Dias",
    toggleDayType: "Alternar tipo de dia",
    deleteWorkoutAction: "Eliminar",
    demoPresetLoaded: "Preset carregado.",
    duplicate: "Duplicar",
    edit: "Editar",
    load: "Carregar",
    loading: "A carregar",
    myWorkouts: "Os meus Treinos",
    newPersonalRecord: "Novo recorde pessoal!",
    noActivePlanTap: "Nenhum plano ativo — toca para criar",
    noExercises: "Sem exercícios.",
    noExercisesYet: "Sem exercícios ainda.",
    noWorkoutsThisWeek: "Sem treinos esta semana ainda.",
    rename: "Renomear",
    renameWorkoutPrompt: "Novo nome do treino:",
    deleteWorkoutTitle: 'Eliminar "{name}"?',
    cannotUndo: "Esta ação não pode ser desfeita.",
    deleteClientTitle: 'Eliminar "{name}"?',
    deleteClientConfirm: "Isto apaga todos os treinos, medidas e notas deste cliente.",
    deletePlanTitle: 'Eliminar "{name}"?',
    deleteMeasureTitle: "Eliminar medida?",
    deleteNoteTitle: "Eliminar nota?",
    deletePlanDayTitle: "Remover este dia do plano?",
    deleteAppointmentTitle: "Eliminar marcação?",
    removeExerciseTitle: "Remover exercício?",
    removeExerciseConfirm: "Remove o exercício e todas as séries registadas nele, neste treino.",
    restart: "Recomeçar",
    restDayBody: "Recupera e volta mais forte.",
    setSingular: "Série",
    share: "Partilhar",
    startWorkoutAria: "Iniciar treino",
    valuesPer100g: "Valores por 100 g",
    weekMuscles: "Músculos esta semana",

  },

  en: {
    history: 'History',
    settings: 'Settings',
    exercisesTitle: 'Exercises',

    homeTitle: 'Workout',
    restDay: 'Rest Day',
    startWorkout: 'Start',
    startAnother: 'Another workout',
    days: 'days',
    steps: 'Steps',
    noWorkoutScheduled: 'No workout scheduled',
    noPlan: 'No active plan',
    choosePlan: 'Choose plan',

    end: 'End',
    cancel: 'Cancel',
    endWorkout: 'End Workout',
    cancelWorkout: 'Cancel Workout',
    minimize: 'Minimize',
    endConfirm: 'End this workout?',
    cancelConfirm: 'Cancel? All progress will be lost.',
    addExercise: 'Exercise',
    reps: 'Reps',
    weight: 'Weight (kg)',
    done: 'Done',
    rest: 'Rest',
    restTimer: 'Rest timer',
    restTimerDone: 'Rest over!',
    startRest: 'Start',
    dragToAdjust: 'Drag to adjust',
    skipRest: 'Skip',
    oneRM: 'Calculate 1RM',
    oneRMResult: 'Estimated 1RM',
    workoutDone: 'Workout complete!',
    totalTime: 'Total time',
    totalSets: 'Total sets',
    totalVolume: 'Total volume',
    great: 'Great work!',
    close: 'Close',
    seconds: 's',
    minutes: 'min',

    searchExercises: 'Search exercises...',
    allTags: 'All',
    noResults: 'No results',
    filters: 'Filters',
    filterBodyPart: 'Body part',
    filterEquipment: 'Equipment',
    rotateBody: 'Rotate',
    clearFilters: 'Clear',
    applyFilters: 'Apply',
    noMediaYet: 'Video coming soon',
    instructions: 'Instructions',
    category: 'Category',
    primaryMuscle: 'Primary muscle',
    secondaryMusclesLabel: 'Secondary muscles',
    toggleCardView: 'Card view',
    toggleListView: 'List view',

    noHistory: 'No history yet',
    historyEmpty: 'Complete a workout to get started.',
    volume: 'volume',
    sets: 'sets',
    exercises: 'exercises',
    importWorkoutTitle: 'Import workout?',
    importWorkout: 'Import',
    setTypeNormal: 'Normal',
    setType_warmup: 'Warmup',
    setType_dropset: 'Dropset',
    setType_superset: 'Superset',
    setType_failure: 'Failure',

    plans: 'Plans',
    newPlan: 'New plan',
    activePlan: 'Active plan',
    setActive: 'Set as active',
    editPlan: 'Edit plan',
    editWorkout: 'Edit workout',
    planName: 'Plan name',
    workoutDay: 'Workout',
    dayRest: 'Rest',
    selectWorkout: 'Select workout',
    workouts: 'Workouts',
    newWorkout: 'New workout',
    workoutName: 'Workout name',
    exerciseNote: 'Note',
    save: 'Save',
    delete: 'Delete',
    back: 'Back',
    confirm: 'Confirm',

    stepsToday: "Today's steps",
    stepsPlaceholder: 'e.g. 8500',
    saveSteps: 'Save',

    // Profile
    profileTitle: 'Profile',
    measures: 'Measures',
    duration: 'Duration',
    weeklyProgress: 'Weekly progress',

    // Statistics page
    daysTrained: 'Days trained',
    totalSessions: 'Total sessions',
    totalReps: 'Total reps',
    bestStreak: 'Best streak',
    personalRecords: 'Personal records',
    personalRecordsLegend: 'estimated 1RM',
    muscleDistribution: 'Muscle distribution',
    noPRs: 'No records yet',
    customizeStats: 'Customize',
    doneEditing: 'Done',
    statsBlock_tiles: 'Workout summary',
    statsBlock_streakCalendar: 'Streak calendar',
    statsBlock_steps: 'Steps',
    nutritionTrend: 'Calories over time',
    nutritionSummary: 'Nutrition summary',
    avgKcal: 'Daily average',
    avgProtein: 'Average protein',
    daysLogged: 'Days logged',
    onTarget: 'On target',
    noNutritionData: 'No meals logged yet. Log food for a few days and your history shows up here.',
    lastNDays: 'Last {n} days',
    statsRange: 'Range',
    custom: 'Custom',
    startDate: 'Start date',
    apply: 'Apply',
    progress: 'Progress',
    noSessionsInRange: 'No workouts in this period.',
    noStatsEnabled: 'No stats enabled — tap Customize to turn blocks on',
    muscleFatigue: 'Muscle fatigue',
    fatigueLevel_fatigued: 'Fatigued',
    fatigueLevel_recovering: 'Recovering',
    fatigueLevel_fresh: 'Fresh',
    fatigueLevel_none: 'No data',
    daysAgo: '{n}d ago',

    // Measures page
    measureValuePlaceholder: 'Value',
    saveMeasure: 'Save',
    noMeasures: 'No measurements logged',
    progression: 'Progression',
    measureInvalidValue: 'Invalid value',
    measureSaveFailed: 'Could not save',
    measureGroup_general: 'General',
    measureGroup_torso: 'Torso',
    measureGroup_arms: 'Arms',
    measureGroup_legs: 'Legs',
    measureType_weight: 'Weight',
    measureType_height: 'Height',
    measureType_bodyFat: 'Body fat %',
    measureType_chest: 'Chest',
    measureType_waist: 'Waist',
    measureType_hips: 'Hips',
    measureType_neck: 'Neck',
    measureType_shoulders: 'Shoulders',
    measureType_biceps: 'Biceps',
    measureType_forearm: 'Forearm',
    measureType_quadriceps: 'Quadriceps',
    measureType_calves: 'Calves',

    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    accentColor: 'Main color',
    colorGreen: 'Green',
    colorBlue: 'Blue',
    colorPurple: 'Purple',
    colorPink: 'Pink',
    colorRed: 'Red',
    colorOrange: 'Orange',
    language: 'Language',
    langPt: 'Português',
    langEn: 'English',

    settingsTitle: 'Settings',
    settingsSections: 'Sections',
    settingsSectionsDesc: 'Choose which parts of the app show up in navigation.',
    sectionGym: 'Workout',
    dataSection: 'Your data',
    dataSectionDesc: 'Save a full copy or just your workouts, and bring data back in.',
    exportData: 'Save a copy',
    exportDataDesc: 'Choose what to save',
    exportChoiceQuestion: 'What do you want to save?',
    exportChoiceFull: 'Full backup (JSON)',
    exportChoiceFullDesc: 'Everything: workouts, plans, measurements, nutrition and settings',
    exportCsv: 'Workouts only (CSV)',
    exportCsvDesc: 'One row per set, for Excel or another app',
    importCsv: 'Import',
    importCsvDesc: 'From a BeefUp copy or another app',
    importChoiceQuestion: 'Where is the file from?',
    importSourceBeefUp: 'A BeefUp copy (CSV)',
    importSourceBeefUpDesc: 'Restores your workouts exactly, without duplicates',
    importSourceOther: 'Another app (CSV)',
    importSourceOtherDesc: 'Strong, Hevy and the like — exercises are matched by name',
    importSourceJson: 'Full backup (JSON)',
    importSourceJsonDesc: 'Restores everything — replaces your current data',
    importBackupTitle: 'Restore backup?',
    importBackupWarn: "This erases your current data and puts the file's data in its place. It can't be undone.",
    restore: 'Restore',
    importDone: 'Imported {w} workouts and {s} sets.',
    importFailed: "Couldn't complete that. Try again.",
    unmatchedExercises: '{n} exercises were not recognised and kept their original name.',
    csvNotBeefUp: 'That file is not a BeefUp copy. Try the "Another app" option.',
    csvNoColumns: "Couldn't find exercise, date and set columns in this CSV.",

    // Nutrition
    nutrition: 'Nutrition',
    calories: 'Calories',
    kcal: 'kcal',
    protein: 'Protein',
    carbs: 'Carbs',
    fat: 'Fat',
    goal: 'Goal',
    water: 'Water',
    addWater: 'Add glass',
    meals: 'Meals',
    breakfast: 'Breakfast',
    morningSnack: 'Morning snack',
    lunch: 'Lunch',
    afternoonSnack: 'Afternoon snack',
    dinner: 'Dinner',
    snack: 'Snack',
    newMeal: 'New meal',
    mealName: 'Meal name',
    deleteMealTitle: 'Delete meal?',
    deleteMealConfirm: 'This removes "{name}" from the list. Already-logged entries stay.',
    addFood: 'Add food',
    searchFood: 'Search foods...',
    serving: 'Serving',
    grams: 'g',
    quantity: 'Quantity',
    customFood: 'Custom food',
    foodName: 'Food name',
    add: 'Add',
    editGoals: 'Edit goals',
    editMealsList: 'Edit meals',
    nutritionGoals: 'Nutrition goals',
    calculator: 'Calculator',
    manual: 'Manual',
    age: 'Age',
    height: 'Height (cm)',
    bodyWeight: 'Weight (kg)',
    sex: 'Sex',
    male: 'Male',
    female: 'Female',
    activity: 'Activity',
    actSedentary: 'Sedentary',
    actLight: 'Light',
    actModerate: 'Moderate',
    actActive: 'Active',
    actVeryActive: 'Very active',
    actFromWorkout: 'From workout data',
    objCut: 'Cut',
    objMaintain: 'Maintain',
    objBulk: 'Bulk',
    calculate: 'Calculate',
    glasses: 'glasses',
    proteinShort: 'P',
    carbsShort: 'C',
    fatShort: 'F',
    deleteFoodTitle: 'Delete entry?',
    deleteFoodConfirm: 'This removes "{name}" from today.',
    macrosFromGoal: 'Macros add up to {kcal} kcal',
    favouriteFood: 'Mark as favourite',

    // Onboarding
    obWelcome: 'BeefUp',
    obWelcomeSub: 'How do you want to use the app?',
    obStart: 'Start',
    obStartDesc: 'Train and track yourself',
    obHelping: 'I am helping others',
    obHelpingDesc: 'Manage clients as a coach',
    obFocusTitle: 'What will you use the app for?',
    obFocusGym: 'Gym',
    obFocusGymDesc: 'Plans and workouts',
    obFocusNutrition: 'Nutrition',
    obFocusNutritionDesc: 'Calories and macros',
    obFocusBoth: 'Both',
    obFocusBothDesc: 'Training and diet together',
    unavailable: 'Unavailable',
    obMeasuresTitle: 'Your measurements',
    obMeasuresSub: 'Optional, skip any field',
    obGoalsTitle: 'Your goal',
    obNext: 'Next',
    obSkip: 'Skip',
    obFinish: 'Finish',
    obDesktopOnly: 'The coach dashboard is available on desktop only.',
    // Explainers
    obExpGymTitle: 'Workouts always with you',
    obExpGymBody: 'Build plans, log sets, and watch your progression over time.',
    obExpNutritionTitle: 'Nutrition made simple',
    obExpNutritionBody: 'Track calories, macros and water with goals calculated for you.',
    obExpMeasuresTitle: 'See your progress',
    obExpMeasuresBody: 'Logging measurements helps you see real results, not just the scale.',
    obExpGoalsTitle: 'All set',
    obExpGoalsBody: 'Your nutrition goals are ready. Let’s get started!',
    resetOnboarding: 'Restart setup',
    resetOnboardingWarn: "You'll go through initial setup again.",

    // Coach dashboard
    dashCalendar: 'Calendar',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    dashClients: 'Clients',
    dashNewClient: 'New client',
    dashClientName: 'Name',
    dashClientInfo: 'Info',
    dashCreate: 'Create',
    dashNoClients: 'No clients yet',
    dashSelectClient: 'Select a client',
    dashNotes: 'Notes',
    dashNotesPlaceholder: 'Write a note about the client...',
    dashAssign: 'Assign',
    dashUnassigned: 'Nothing scheduled',
    dashGym: 'Gym',
    dashMeasures: 'Measures',
    dashDelete: 'Delete client',
    dashOverview: 'Overview',
    dashTime: 'Time',
    dashSync: 'Sync',
    dashSyncSetup: 'Firebase setup',
    dashSyncDesc: 'Paste the firebaseConfig object from your Firebase project. Data lives in your own Firestore, we extract only what is needed.',
    dashConfigSaved: 'Config saved.',
    dashPush: 'Push clients',
    dashPull: 'Pull clients',
    dashPushed: 'Pushed',
    dashPulled: 'Pulled',
    // Moved out of inline lang ternaries
    advanced: "Advanced",
    bodyBack: "Back",
    bodyFront: "Front",
    choose: "Choose",
    copySuffix: "copy",
    createNewWorkout: "+ Create new workout",
    currentPlan: "Current Plan",
    currentStreak: "Current streak",
    currentStreakShort: "Current streak",
    daysTitle: "Days",
    toggleDayType: "Toggle day type",
    deleteWorkoutAction: "Delete",
    demoPresetLoaded: "Demo preset loaded.",
    duplicate: "Duplicate",
    edit: "Edit",
    load: "Load",
    loading: "Loading",
    myWorkouts: "My Workouts",
    newPersonalRecord: "New personal record!",
    noActivePlanTap: "No active plan — tap to create",
    noExercises: "No exercises.",
    noExercisesYet: "No exercises yet.",
    noWorkoutsThisWeek: "No workouts logged this week yet.",
    rename: "Rename",
    renameWorkoutPrompt: "New workout name:",
    deleteWorkoutTitle: 'Delete "{name}"?',
    cannotUndo: "This action cannot be undone.",
    deleteClientTitle: 'Delete "{name}"?',
    deleteClientConfirm: "This deletes all of this client's workouts, measurements and notes.",
    deletePlanTitle: 'Delete "{name}"?',
    deleteMeasureTitle: "Delete measurement?",
    deleteNoteTitle: "Delete note?",
    deletePlanDayTitle: "Remove this day from the plan?",
    deleteAppointmentTitle: "Delete appointment?",
    removeExerciseTitle: "Remove exercise?",
    removeExerciseConfirm: "This removes the exercise and every set logged under it, for this workout.",
    restart: "Restart",
    restDayBody: "Recover and come back stronger.",
    setSingular: "Set",
    share: "Share",
    startWorkoutAria: "Start workout",
    valuesPer100g: "Values per 100 g",
    weekMuscles: "This week's muscles",

  },
}

export default strings
